import type { SeedLibrary } from "./types.js";

export const BACKEND_SEED_LIBRARIES: SeedLibrary[] = [
  // ─── Database / ORM ───────────────────────────────────────────────────────────
  {
    name: "Prisma",
    slug: "prisma",
    description: "Next-generation Node.js and TypeScript ORM for PostgreSQL, MySQL, SQLite",
    npm_package: "prisma",
    github_repo: "prisma/prisma",
    docs_url: "https://www.prisma.io/docs",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://www.prisma.io/docs/getting-started" },
      { type: "api", url: "https://www.prisma.io/docs/orm/reference/prisma-client-reference" },
      { type: "npm", url: "https://npmjs.com/package/prisma" },
      { type: "github", url: "https://github.com/prisma/prisma" },
    ],
  },
  {
    name: "Drizzle ORM",
    slug: "drizzle",
    description: "Headless TypeScript ORM with a SQL-like query API",
    npm_package: "drizzle-orm",
    github_repo: "drizzle-team/drizzle-orm",
    docs_url: "https://orm.drizzle.team/docs/overview",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://orm.drizzle.team/docs/overview" },
      { type: "npm", url: "https://npmjs.com/package/drizzle-orm" },
      { type: "github", url: "https://github.com/drizzle-team/drizzle-orm" },
    ],
  },
  {
    name: "TypeORM",
    slug: "typeorm",
    description: "ORM for TypeScript and JavaScript — Active Record and Data Mapper patterns",
    npm_package: "typeorm",
    github_repo: "typeorm/typeorm",
    docs_url: "https://typeorm.io",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://typeorm.io" },
      { type: "npm", url: "https://npmjs.com/package/typeorm" },
      { type: "github", url: "https://github.com/typeorm/typeorm" },
    ],
  },
  {
    name: "Mongoose",
    slug: "mongoose",
    description: "Elegant MongoDB object modeling for Node.js",
    npm_package: "mongoose",
    github_repo: "Automattic/mongoose",
    docs_url: "https://mongoosejs.com/docs",
    tags: ["database", "mongodb", "odm", "nosql"],
    links: [
      { type: "docs", url: "https://mongoosejs.com/docs/guide.html" },
      { type: "api", url: "https://mongoosejs.com/docs/api/mongoose.html" },
      { type: "npm", url: "https://npmjs.com/package/mongoose" },
      { type: "github", url: "https://github.com/Automattic/mongoose" },
    ],
  },
  {
    name: "Supabase",
    slug: "supabase",
    description: "Open source Firebase alternative — PostgreSQL, Auth, Storage, Realtime",
    npm_package: "@supabase/supabase-js",
    github_repo: "supabase/supabase",
    docs_url: "https://supabase.com/docs",
    tags: ["database", "backend-as-a-service", "postgresql", "realtime"],
    links: [
      { type: "docs", url: "https://supabase.com/docs/reference/javascript/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@supabase/supabase-js" },
      { type: "github", url: "https://github.com/supabase/supabase" },
    ],
  },
  {
    name: "Turso",
    slug: "turso",
    description: "SQLite for production — edge-native distributed database",
    npm_package: "@libsql/client",
    github_repo: "tursodatabase/turso-client-ts",
    docs_url: "https://docs.turso.tech",
    tags: ["database", "sqlite", "edge", "distributed"],
    links: [
      { type: "docs", url: "https://docs.turso.tech/sdk/ts/reference" },
      { type: "npm", url: "https://npmjs.com/package/@libsql/client" },
      { type: "github", url: "https://github.com/tursodatabase/turso-client-ts" },
    ],
  },
  {
    name: "Redis",
    slug: "redis",
    description: "In-memory data structure store — caching, pub/sub, queues",
    npm_package: "redis",
    github_repo: "redis/node-redis",
    docs_url: "https://redis.io/docs",
    tags: ["database", "cache", "nosql", "pub-sub"],
    links: [
      { type: "docs", url: "https://redis.io/docs/latest/develop/connect/clients/nodejs" },
      { type: "api", url: "https://redis.io/commands" },
      { type: "npm", url: "https://npmjs.com/package/redis" },
      { type: "github", url: "https://github.com/redis/node-redis" },
    ],
  },

  // ─── Validation / Schema ──────────────────────────────────────────────────────
  {
    name: "Zod",
    slug: "zod",
    description: "TypeScript-first schema declaration and validation library",
    npm_package: "zod",
    github_repo: "colinhacks/zod",
    docs_url: "https://zod.dev",
    tags: ["typescript", "validation", "schema"],
    links: [
      { type: "docs", url: "https://zod.dev/?id=introduction" },
      { type: "npm", url: "https://npmjs.com/package/zod" },
      { type: "github", url: "https://github.com/colinhacks/zod" },
    ],
  },
  {
    name: "Valibot",
    slug: "valibot",
    description: "The modular and type-safe schema library for validating structural data",
    npm_package: "valibot",
    github_repo: "fabian-hiller/valibot",
    docs_url: "https://valibot.dev/guides/introduction",
    tags: ["typescript", "validation", "schema"],
    links: [
      { type: "docs", url: "https://valibot.dev" },
      { type: "npm", url: "https://npmjs.com/package/valibot" },
      { type: "github", url: "https://github.com/fabian-hiller/valibot" },
    ],
  },

  // ─── HTTP / API clients ───────────────────────────────────────────────────────
  {
    name: "Axios",
    slug: "axios",
    description: "Promise-based HTTP client for the browser and Node.js",
    npm_package: "axios",
    github_repo: "axios/axios",
    docs_url: "https://axios-http.com/docs/intro",
    tags: ["http", "client", "promise"],
    links: [
      { type: "docs", url: "https://axios-http.com/docs/intro" },
      { type: "api", url: "https://axios-http.com/docs/api_intro" },
      { type: "npm", url: "https://npmjs.com/package/axios" },
      { type: "github", url: "https://github.com/axios/axios" },
    ],
  },
  {
    name: "ky",
    slug: "ky",
    description: "Tiny and elegant HTTP client based on Fetch API",
    npm_package: "ky",
    github_repo: "sindresorhus/ky",
    docs_url: "https://github.com/sindresorhus/ky",
    tags: ["http", "client", "fetch"],
    links: [
      { type: "docs", url: "https://github.com/sindresorhus/ky#readme" },
      { type: "npm", url: "https://npmjs.com/package/ky" },
      { type: "github", url: "https://github.com/sindresorhus/ky" },
    ],
  },

  // ─── Auth ─────────────────────────────────────────────────────────────────────
  {
    name: "Auth.js",
    slug: "authjs",
    description: "Authentication for the web — supports 80+ OAuth providers",
    npm_package: "next-auth",
    github_repo: "nextauthjs/next-auth",
    docs_url: "https://authjs.dev/getting-started",
    tags: ["auth", "oauth", "jwt", "session"],
    links: [
      { type: "docs", url: "https://authjs.dev" },
      { type: "api", url: "https://authjs.dev/reference/core" },
      { type: "npm", url: "https://npmjs.com/package/next-auth" },
      { type: "github", url: "https://github.com/nextauthjs/next-auth" },
    ],
  },
  {
    name: "Lucia",
    slug: "lucia",
    description: "Simple and flexible auth library for TypeScript",
    npm_package: "lucia",
    github_repo: "lucia-auth/lucia",
    docs_url: "https://lucia-auth.com",
    tags: ["auth", "session", "typescript"],
    links: [
      { type: "docs", url: "https://lucia-auth.com/getting-started" },
      { type: "npm", url: "https://npmjs.com/package/lucia" },
      { type: "github", url: "https://github.com/lucia-auth/lucia" },
    ],
  },
  {
    name: "Better Auth",
    slug: "better-auth",
    description: "The most comprehensive authentication framework for TypeScript",
    npm_package: "better-auth",
    github_repo: "better-auth/better-auth",
    docs_url: "https://www.better-auth.com/docs/introduction",
    tags: ["auth", "session", "typescript", "framework"],
    links: [
      { type: "docs", url: "https://www.better-auth.com/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/better-auth" },
      { type: "github", url: "https://github.com/better-auth/better-auth" },
    ],
  },

  // ─── AI / ML ──────────────────────────────────────────────────────────────────
  {
    name: "Vercel AI SDK",
    slug: "vercel-ai-sdk",
    description: "Build AI-powered products with React, Svelte, Vue, and Node.js",
    npm_package: "ai",
    github_repo: "vercel/ai",
    docs_url: "https://ai-sdk.dev/docs",
    source_type: "llms_txt",
    source_url: "https://ai-sdk.dev/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "streaming", "typescript"],
    links: [
      { type: "docs", url: "https://ai-sdk.dev/docs/introduction" },
      { type: "api", url: "https://ai-sdk.dev/docs/reference/ai-sdk-core" },
      { type: "npm", url: "https://npmjs.com/package/ai" },
      { type: "github", url: "https://github.com/vercel/ai" },
    ],
  },
  {
    name: "Anthropic SDK",
    slug: "anthropic",
    description: "Official TypeScript/JavaScript SDK for the Anthropic API (Claude)",
    npm_package: "@anthropic-ai/sdk",
    github_repo: "anthropics/anthropic-sdk-typescript",
    docs_url: "https://docs.anthropic.com",
    source_type: "llms_txt",
    source_url: "https://docs.anthropic.com/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "claude", "sdk"],
    links: [
      { type: "docs", url: "https://docs.anthropic.com/en/api/getting-started" },
      { type: "api", url: "https://docs.anthropic.com/en/api/messages" },
      { type: "npm", url: "https://npmjs.com/package/@anthropic-ai/sdk" },
      { type: "github", url: "https://github.com/anthropics/anthropic-sdk-typescript" },
    ],
  },
  {
    name: "OpenAI SDK",
    slug: "openai",
    description: "Official TypeScript/JavaScript SDK for the OpenAI API",
    npm_package: "openai",
    github_repo: "openai/openai-node",
    docs_url: "https://developers.openai.com/api/docs",
    source_type: "api",
    source_url: "https://developers.openai.com/api/docs",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "gpt", "sdk", "api"],
    links: [
      { type: "docs", url: "https://developers.openai.com/api/docs" },
      { type: "api", url: "https://developers.openai.com/api/reference/overview" },
      { type: "npm", url: "https://npmjs.com/package/openai" },
      { type: "github", url: "https://github.com/openai/openai-node" },
    ],
  },
  {
    name: "xAI API",
    slug: "xai",
    description: "xAI Grok API and SDK documentation",
    npm_package: "@ai-sdk/xai",
    github_repo: "xai-org/xai-sdk-python",
    docs_url: "https://docs.x.ai/overview",
    source_type: "llms_txt",
    source_url: "https://docs.x.ai/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "grok", "sdk", "api"],
    links: [
      { type: "docs", url: "https://docs.x.ai/overview" },
      { type: "api", url: "https://docs.x.ai/developers/rest-api-reference" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/xai" },
      { type: "github", url: "https://github.com/xai-org/xai-sdk-python" },
    ],
  },
  {
    name: "DeepSeek API",
    slug: "deepseek",
    description: "DeepSeek API documentation and OpenAI-compatible model access",
    npm_package: "@ai-sdk/deepseek",
    docs_url: "https://api-docs.deepseek.com/",
    source_type: "api",
    source_url: "https://api-docs.deepseek.com/",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "reasoning", "sdk", "api"],
    links: [
      { type: "docs", url: "https://api-docs.deepseek.com/" },
      { type: "api", url: "https://api-docs.deepseek.com/api/create-chat-completion" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/deepseek" },
    ],
  },
  {
    name: "Google Gemini API",
    slug: "gemini",
    description: "Google Gemini API documentation for generative AI applications",
    npm_package: "@ai-sdk/google",
    docs_url: "https://ai.google.dev/gemini-api/docs",
    source_type: "llms_txt",
    source_url: "https://ai.google.dev/gemini-api/docs/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "gemini", "google", "api"],
    links: [
      { type: "docs", url: "https://ai.google.dev/gemini-api/docs" },
      { type: "api", url: "https://ai.google.dev/api" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/google" },
    ],
  },
  {
    name: "Mistral AI API",
    slug: "mistral",
    description: "Mistral AI model, API, and SDK documentation",
    npm_package: "@ai-sdk/mistral",
    docs_url: "https://docs.mistral.ai/",
    source_type: "llms_txt",
    source_url: "https://docs.mistral.ai/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "mistral", "sdk", "api"],
    links: [
      { type: "docs", url: "https://docs.mistral.ai/" },
      { type: "api", url: "https://docs.mistral.ai/api/" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/mistral" },
    ],
  },
  {
    name: "Cohere API",
    slug: "cohere",
    description: "Cohere API, models, reranking, and embeddings documentation",
    npm_package: "@ai-sdk/cohere",
    docs_url: "https://docs.cohere.com/",
    source_type: "llms_txt",
    source_url: "https://docs.cohere.com/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "rerank", "embeddings", "api"],
    links: [
      { type: "docs", url: "https://docs.cohere.com/" },
      { type: "api", url: "https://docs.cohere.com/reference/about" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/cohere" },
    ],
  },
  {
    name: "Groq API",
    slug: "groq",
    description: "GroqCloud low-latency inference API documentation",
    npm_package: "@ai-sdk/groq",
    docs_url: "https://console.groq.com/docs/overview",
    source_type: "llms_txt",
    source_url: "https://console.groq.com/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "inference", "openai-compatible", "api"],
    links: [
      { type: "docs", url: "https://console.groq.com/docs/overview" },
      { type: "api", url: "https://console.groq.com/docs/api-reference" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/groq" },
    ],
  },
  {
    name: "Perplexity API",
    slug: "perplexity",
    description: "Perplexity Sonar, Search, Agent, and Embeddings API documentation",
    npm_package: "@ai-sdk/perplexity",
    docs_url: "https://docs.perplexity.ai/docs/getting-started/overview",
    source_type: "llms_txt",
    source_url: "https://docs.perplexity.ai/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "search", "research", "api"],
    links: [
      { type: "docs", url: "https://docs.perplexity.ai/docs/getting-started/overview" },
      { type: "api", url: "https://docs.perplexity.ai/docs/getting-started/quickstart" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/perplexity" },
    ],
  },
  {
    name: "Together AI API",
    slug: "together-ai",
    description: "Together AI model inference, training, and OpenAI-compatible API docs",
    npm_package: "@ai-sdk/togetherai",
    docs_url: "https://docs.together.ai/intro",
    source_type: "llms_txt",
    source_url: "https://docs.together.ai/llms.txt",
    freshness_days: 1,
    priority: 25,
    tags: ["ai", "llm", "open-source-models", "inference", "api"],
    links: [
      { type: "docs", url: "https://docs.together.ai/intro" },
      { type: "api", url: "https://docs.together.ai/reference/chat-completions" },
      { type: "npm", url: "https://npmjs.com/package/@ai-sdk/togetherai" },
    ],
  },
  {
    name: "LangChain.js",
    slug: "langchainjs",
    description: "Framework for building LLM-powered applications in TypeScript",
    npm_package: "langchain",
    github_repo: "langchain-ai/langchainjs",
    docs_url: "https://js.langchain.com/docs",
    tags: ["ai", "llm", "chains", "agents", "rag"],
    links: [
      { type: "docs", url: "https://js.langchain.com/docs/introduction" },
      { type: "api", url: "https://api.js.langchain.com" },
      { type: "npm", url: "https://npmjs.com/package/langchain" },
      { type: "github", url: "https://github.com/langchain-ai/langchainjs" },
    ],
  },
  {
    name: "Mastra",
    slug: "mastra",
    description: "TypeScript AI framework for building agents, workflows, and RAG pipelines",
    npm_package: "@mastra/core",
    github_repo: "mastra-ai/mastra",
    docs_url: "https://mastra.ai/docs",
    tags: ["ai", "agents", "workflows", "typescript"],
    links: [
      { type: "docs", url: "https://mastra.ai/docs" },
      { type: "npm", url: "https://npmjs.com/package/@mastra/core" },
      { type: "github", url: "https://github.com/mastra-ai/mastra" },
    ],
  },
  {
    name: "Model Context Protocol SDK",
    slug: "mcp-sdk",
    description: "TypeScript SDK for building MCP servers and clients",
    npm_package: "@modelcontextprotocol/sdk",
    github_repo: "modelcontextprotocol/typescript-sdk",
    docs_url: "https://modelcontextprotocol.io/docs",
    tags: ["ai", "mcp", "llm", "tools", "sdk"],
    links: [
      { type: "docs", url: "https://modelcontextprotocol.io/docs/concepts/architecture" },
      { type: "api", url: "https://modelcontextprotocol.io/docs/concepts/tools" },
      { type: "npm", url: "https://npmjs.com/package/@modelcontextprotocol/sdk" },
      { type: "github", url: "https://github.com/modelcontextprotocol/typescript-sdk" },
    ],
  },

  // ─── Cloud / Infrastructure ───────────────────────────────────────────────────
  {
    name: "AWS SDK v3",
    slug: "aws-sdk",
    description: "Modular AWS SDK for JavaScript and TypeScript",
    npm_package: "@aws-sdk/client-s3",
    github_repo: "aws/aws-sdk-js-v3",
    docs_url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest",
    tags: ["cloud", "aws", "sdk", "s3", "lambda"],
    links: [
      { type: "docs", url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest" },
      { type: "npm", url: "https://npmjs.com/package/@aws-sdk/client-s3" },
      { type: "github", url: "https://github.com/aws/aws-sdk-js-v3" },
    ],
  },
  {
    name: "Cloudflare Workers",
    slug: "cloudflare-workers",
    description: "Serverless JavaScript/TypeScript at the edge — Wrangler + Workers API",
    npm_package: "wrangler",
    github_repo: "cloudflare/workers-sdk",
    docs_url: "https://developers.cloudflare.com/workers",
    tags: ["cloud", "cloudflare", "edge", "serverless"],
    links: [
      { type: "docs", url: "https://developers.cloudflare.com/workers/get-started/guide" },
      { type: "api", url: "https://developers.cloudflare.com/workers/runtime-apis" },
      { type: "npm", url: "https://npmjs.com/package/wrangler" },
      { type: "github", url: "https://github.com/cloudflare/workers-sdk" },
    ],
  },
  {
    name: "Stripe",
    slug: "stripe",
    description: "Payment processing APIs — SDK for Node.js/TypeScript",
    npm_package: "stripe",
    github_repo: "stripe/stripe-node",
    docs_url: "https://docs.stripe.com/api",
    source_type: "openapi",
    source_url: "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
    tags: ["payments", "api", "sdk"],
    links: [
      { type: "docs", url: "https://docs.stripe.com/api" },
      { type: "api", url: "https://docs.stripe.com/api#intro" },
      { type: "npm", url: "https://npmjs.com/package/stripe" },
      { type: "github", url: "https://github.com/stripe/stripe-node" },
    ],
  },
  {
    name: "Slack API",
    slug: "slack",
    description: "Slack platform APIs, apps, web API, and workflow automation docs",
    npm_package: "@slack/web-api",
    github_repo: "slackapi/node-slack-sdk",
    docs_url: "https://docs.slack.dev",
    tags: ["saas", "api", "chat", "collaboration", "webhooks"],
    links: [
      { type: "docs", url: "https://docs.slack.dev" },
      { type: "api", url: "https://docs.slack.dev/apis/web-api" },
      { type: "npm", url: "https://npmjs.com/package/@slack/web-api" },
      { type: "github", url: "https://github.com/slackapi/node-slack-sdk" },
    ],
  },
  {
    name: "Notion API",
    slug: "notion",
    description: "Notion REST API and workspace automation documentation",
    npm_package: "@notionhq/client",
    github_repo: "makenotion/notion-sdk-js",
    docs_url: "https://developers.notion.com",
    tags: ["saas", "api", "workspace", "documents", "automation"],
    links: [
      { type: "docs", url: "https://developers.notion.com/guides/get-started/overview" },
      { type: "api", url: "https://developers.notion.com/reference/intro" },
      { type: "npm", url: "https://npmjs.com/package/@notionhq/client" },
      { type: "github", url: "https://github.com/makenotion/notion-sdk-js" },
    ],
  },
  {
    name: "Linear API",
    slug: "linear",
    description: "Linear GraphQL API, webhooks, and TypeScript SDK documentation",
    npm_package: "@linear/sdk",
    github_repo: "linear/linear",
    docs_url: "https://linear.app/developers",
    tags: ["saas", "api", "graphql", "issues", "webhooks"],
    links: [
      { type: "docs", url: "https://linear.app/developers" },
      { type: "api", url: "https://linear.app/developers/graphql" },
      { type: "tutorial", url: "https://linear.app/docs/api-and-webhooks" },
      { type: "npm", url: "https://npmjs.com/package/@linear/sdk" },
      { type: "github", url: "https://github.com/linear/linear" },
    ],
  },
  {
    name: "GitHub REST API",
    slug: "github-rest",
    description: "GitHub REST API documentation for automation and integrations",
    npm_package: "@octokit/rest",
    github_repo: "octokit/rest.js",
    docs_url: "https://docs.github.com/en/rest",
    source_type: "openapi",
    source_url: "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
    tags: ["saas", "api", "github", "automation", "rest"],
    links: [
      { type: "docs", url: "https://docs.github.com/en/rest" },
      { type: "api", url: "https://docs.github.com/rest/guides/getting-started-with-the-rest-api" },
      { type: "npm", url: "https://npmjs.com/package/@octokit/rest" },
      { type: "github", url: "https://github.com/octokit/rest.js" },
    ],
  },
  {
    name: "Jira Cloud REST API",
    slug: "jira",
    description: "Atlassian Jira Cloud platform REST API documentation",
    npm_package: undefined,
    docs_url: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    tags: ["saas", "api", "jira", "atlassian", "issues"],
    links: [
      { type: "docs", url: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/" },
      { type: "api", url: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/" },
    ],
  },
  {
    name: "Shopify API",
    slug: "shopify",
    description: "Shopify Admin APIs, app development, and storefront API docs",
    npm_package: "@shopify/shopify-api",
    github_repo: "Shopify/shopify-api-js",
    docs_url: "https://shopify.dev/docs/api",
    tags: ["saas", "api", "commerce", "graphql", "apps"],
    links: [
      { type: "docs", url: "https://shopify.dev/docs/api" },
      { type: "api", url: "https://shopify.dev/docs/api/admin-graphql/latest" },
      { type: "npm", url: "https://npmjs.com/package/@shopify/shopify-api" },
      { type: "github", url: "https://github.com/Shopify/shopify-api-js" },
    ],
  },
  {
    name: "HubSpot API",
    slug: "hubspot",
    description: "HubSpot developer platform, CRM APIs, and date-versioned API reference",
    npm_package: "@hubspot/api-client",
    github_repo: "HubSpot/hubspot-api-nodejs",
    docs_url: "https://developers.hubspot.com/docs",
    source_type: "openapi",
    source_url: "https://raw.githubusercontent.com/HubSpot/HubSpot-public-api-spec-collection/main/PublicApiSpecs/CRM/Contacts/Rollouts/424/v3/contacts.json",
    tags: ["saas", "api", "crm", "marketing", "automation"],
    links: [
      { type: "docs", url: "https://developers.hubspot.com/docs" },
      { type: "api", url: "https://developers.hubspot.com/docs/api-reference/latest/overview" },
      { type: "npm", url: "https://npmjs.com/package/@hubspot/api-client" },
      { type: "github", url: "https://github.com/HubSpot/hubspot-api-nodejs" },
    ],
  },
  {
    name: "Discord API",
    slug: "discord",
    description: "Discord developer platform REST, Gateway, and app API documentation",
    npm_package: "discord.js",
    github_repo: "discord/discord-api-docs",
    docs_url: "https://docs.discord.com/developers/intro",
    tags: ["saas", "api", "chat", "bots", "gateway"],
    links: [
      { type: "docs", url: "https://docs.discord.com/developers/intro" },
      { type: "api", url: "https://docs.discord.com/developers/reference" },
      { type: "npm", url: "https://npmjs.com/package/discord.js" },
      { type: "github", url: "https://github.com/discord/discord-api-docs" },
    ],
  },
  {
    name: "Resend",
    slug: "resend",
    description: "Email API for developers — send transactional emails at scale",
    npm_package: "resend",
    github_repo: "resend/resend-node",
    docs_url: "https://resend.com/docs",
    tags: ["email", "api", "transactional"],
    links: [
      { type: "docs", url: "https://resend.com/docs/introduction" },
      { type: "api", url: "https://resend.com/docs/api-reference/introduction" },
      { type: "npm", url: "https://npmjs.com/package/resend" },
      { type: "github", url: "https://github.com/resend/resend-node" },
    ],
  },
  {
    name: "Upstash",
    slug: "upstash",
    description: "Serverless Redis and Kafka for the edge — JS/TS SDK",
    npm_package: "@upstash/redis",
    github_repo: "upstash/upstash-redis",
    docs_url: "https://upstash.com/docs/redis/overall/getstarted",
    tags: ["database", "redis", "serverless", "edge"],
    links: [
      { type: "docs", url: "https://upstash.com/docs/redis/sdks/ts/overview" },
      { type: "npm", url: "https://npmjs.com/package/@upstash/redis" },
      { type: "github", url: "https://github.com/upstash/upstash-redis" },
    ],
  },

  // ─── Runtimes ─────────────────────────────────────────────────────────────────
  {
    name: "Bun",
    slug: "bun",
    description: "Fast all-in-one JavaScript runtime with bundler, test runner, and package manager",
    npm_package: "bun-types",
    github_repo: "oven-sh/bun",
    docs_url: "https://bun.sh/docs",
    tags: ["runtime", "javascript", "typescript", "bundler"],
    links: [
      { type: "docs", url: "https://bun.sh/docs" },
      { type: "api", url: "https://bun.sh/docs/api/http" },
      { type: "npm", url: "https://npmjs.com/package/bun-types" },
      { type: "github", url: "https://github.com/oven-sh/bun" },
    ],
  },
  {
    name: "Deno",
    slug: "deno",
    description: "A modern runtime for JavaScript and TypeScript",
    npm_package: undefined,
    github_repo: "denoland/deno",
    docs_url: "https://docs.deno.com",
    tags: ["runtime", "javascript", "typescript", "secure"],
    links: [
      { type: "docs", url: "https://docs.deno.com/runtime" },
      { type: "api", url: "https://docs.deno.com/api/deno" },
      { type: "github", url: "https://github.com/denoland/deno" },
    ],
  },
  {
    name: "Node.js",
    slug: "nodejs",
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine",
    npm_package: undefined,
    github_repo: "nodejs/node",
    docs_url: "https://nodejs.org/en/docs",
    tags: ["runtime", "javascript", "server"],
    links: [
      { type: "docs", url: "https://nodejs.org/en/docs/guides" },
      { type: "api", url: "https://nodejs.org/api" },
      { type: "github", url: "https://github.com/nodejs/node" },
    ],
  },
];
