import type { SeedLibrary } from "./types.js";

export const ECOSYSTEM_SEED_LIBRARIES: SeedLibrary[] = [
  // ─── Mobile ───────────────────────────────────────────────────────────────────
  {
    name: "React Native",
    slug: "react-native",
    description: "Build native apps for Android and iOS using React",
    npm_package: "react-native",
    github_repo: "facebook/react-native",
    docs_url: "https://reactnative.dev/docs/getting-started",
    tags: ["mobile", "react", "android", "ios"],
    links: [
      { type: "docs", url: "https://reactnative.dev/docs/getting-started" },
      { type: "api", url: "https://reactnative.dev/docs/components-and-apis" },
      { type: "npm", url: "https://npmjs.com/package/react-native" },
      { type: "github", url: "https://github.com/facebook/react-native" },
    ],
  },
  {
    name: "Expo",
    slug: "expo",
    description: "An open-source platform for making universal native apps with React",
    npm_package: "expo",
    github_repo: "expo/expo",
    docs_url: "https://docs.expo.dev",
    tags: ["mobile", "react-native", "android", "ios", "web"],
    links: [
      { type: "docs", url: "https://docs.expo.dev/get-started/introduction" },
      { type: "api", url: "https://docs.expo.dev/versions/latest" },
      { type: "npm", url: "https://npmjs.com/package/expo" },
      { type: "github", url: "https://github.com/expo/expo" },
    ],
  },

  // ─── Utilities ────────────────────────────────────────────────────────────────
  {
    name: "date-fns",
    slug: "date-fns",
    description: "Modern JavaScript date utility library",
    npm_package: "date-fns",
    github_repo: "date-fns/date-fns",
    docs_url: "https://date-fns.org/docs",
    tags: ["utility", "dates", "javascript"],
    links: [
      { type: "docs", url: "https://date-fns.org/docs/Getting-Started" },
      { type: "api", url: "https://date-fns.org/v3/docs" },
      { type: "npm", url: "https://npmjs.com/package/date-fns" },
      { type: "github", url: "https://github.com/date-fns/date-fns" },
    ],
  },
  {
    name: "Lodash",
    slug: "lodash",
    description: "A modern JavaScript utility library delivering modularity and performance",
    npm_package: "lodash",
    github_repo: "lodash/lodash",
    docs_url: "https://lodash.com/docs",
    tags: ["utility", "javascript", "functional"],
    links: [
      { type: "docs", url: "https://lodash.com/docs" },
      { type: "npm", url: "https://npmjs.com/package/lodash" },
      { type: "github", url: "https://github.com/lodash/lodash" },
    ],
  },
  {
    name: "Effect",
    slug: "effect",
    description: "Powerful TypeScript framework for building complex applications",
    npm_package: "effect",
    github_repo: "Effect-TS/effect",
    docs_url: "https://effect.website/docs",
    tags: ["typescript", "functional", "effects", "fp"],
    links: [
      { type: "docs", url: "https://effect.website/docs/getting-started/introduction" },
      { type: "api", url: "https://effect-ts.github.io/effect" },
      { type: "npm", url: "https://npmjs.com/package/effect" },
      { type: "github", url: "https://github.com/Effect-TS/effect" },
    ],
  },

  // ─── Python ───────────────────────────────────────────────────────────────────
  {
    name: "FastAPI",
    slug: "fastapi",
    description: "Modern, fast web framework for building APIs with Python type hints",
    npm_package: undefined,
    github_repo: "fastapi/fastapi",
    docs_url: "https://fastapi.tiangolo.com",
    tags: ["python", "api", "framework", "async"],
    links: [
      { type: "docs", url: "https://fastapi.tiangolo.com/tutorial" },
      { type: "api", url: "https://fastapi.tiangolo.com/reference" },
      { type: "github", url: "https://github.com/fastapi/fastapi" },
    ],
  },
  {
    name: "Django",
    slug: "django",
    description: "The web framework for perfectionists with deadlines",
    npm_package: undefined,
    github_repo: "django/django",
    docs_url: "https://docs.djangoproject.com",
    tags: ["python", "framework", "web", "orm"],
    links: [
      { type: "docs", url: "https://docs.djangoproject.com/en/stable" },
      { type: "github", url: "https://github.com/django/django" },
    ],
  },
  {
    name: "Flask",
    slug: "flask",
    description: "A lightweight WSGI web application framework in Python",
    npm_package: undefined,
    github_repo: "pallets/flask",
    docs_url: "https://flask.palletsprojects.com",
    tags: ["python", "framework", "web", "wsgi"],
    links: [
      { type: "docs", url: "https://flask.palletsprojects.com/en/stable" },
      { type: "api", url: "https://flask.palletsprojects.com/en/stable/api" },
      { type: "github", url: "https://github.com/pallets/flask" },
    ],
  },
  {
    name: "SQLAlchemy",
    slug: "sqlalchemy",
    description: "The Python SQL toolkit and Object Relational Mapper",
    npm_package: undefined,
    github_repo: "sqlalchemy/sqlalchemy",
    docs_url: "https://docs.sqlalchemy.org",
    tags: ["python", "database", "orm", "sql"],
    links: [
      { type: "docs", url: "https://docs.sqlalchemy.org/en/20/tutorial" },
      { type: "api", url: "https://docs.sqlalchemy.org/en/20/orm/mapping_api.html" },
      { type: "github", url: "https://github.com/sqlalchemy/sqlalchemy" },
    ],
  },
  {
    name: "Pydantic",
    slug: "pydantic",
    description: "Data validation using Python type annotations",
    npm_package: undefined,
    github_repo: "pydantic/pydantic",
    docs_url: "https://docs.pydantic.dev",
    tags: ["python", "validation", "types"],
    links: [
      { type: "docs", url: "https://docs.pydantic.dev/latest" },
      { type: "api", url: "https://docs.pydantic.dev/latest/api/main" },
      { type: "github", url: "https://github.com/pydantic/pydantic" },
    ],
  },
  {
    name: "Pandas",
    slug: "pandas",
    description: "Powerful Python data analysis and manipulation library",
    npm_package: undefined,
    github_repo: "pandas-dev/pandas",
    docs_url: "https://pandas.pydata.org/docs",
    tags: ["python", "data-science", "dataframes", "analysis"],
    links: [
      { type: "docs", url: "https://pandas.pydata.org/docs/getting_started" },
      { type: "api", url: "https://pandas.pydata.org/docs/reference" },
      { type: "github", url: "https://github.com/pandas-dev/pandas" },
    ],
  },
  {
    name: "NumPy",
    slug: "numpy",
    description: "Fundamental package for scientific computing with Python",
    npm_package: undefined,
    github_repo: "numpy/numpy",
    docs_url: "https://numpy.org/doc",
    tags: ["python", "data-science", "arrays", "math"],
    links: [
      { type: "docs", url: "https://numpy.org/doc/stable/user/quickstart.html" },
      { type: "api", url: "https://numpy.org/doc/stable/reference" },
      { type: "github", url: "https://github.com/numpy/numpy" },
    ],
  },
  {
    name: "PyTorch",
    slug: "pytorch",
    description: "An open source machine learning framework for Python",
    npm_package: undefined,
    github_repo: "pytorch/pytorch",
    docs_url: "https://pytorch.org/docs",
    tags: ["python", "ml", "deep-learning", "tensors"],
    links: [
      { type: "docs", url: "https://pytorch.org/docs/stable/index.html" },
      { type: "api", url: "https://pytorch.org/docs/stable/torch.html" },
      { type: "github", url: "https://github.com/pytorch/pytorch" },
    ],
  },

  // ─── DevOps / Infra ───────────────────────────────────────────────────────────
  {
    name: "Docker",
    slug: "docker",
    description: "Build, run, and ship applications in containers",
    npm_package: undefined,
    github_repo: "docker/cli",
    docs_url: "https://docs.docker.com",
    tags: ["devops", "containers", "deployment"],
    links: [
      { type: "docs", url: "https://docs.docker.com/get-started" },
      { type: "api", url: "https://docs.docker.com/engine/api" },
      { type: "github", url: "https://github.com/docker/cli" },
    ],
  },
  {
    name: "GitHub Actions",
    slug: "github-actions",
    description: "Automate, customize, and execute software development workflows in GitHub",
    npm_package: undefined,
    github_repo: "actions/toolkit",
    docs_url: "https://docs.github.com/en/actions",
    tags: ["devops", "ci-cd", "automation"],
    links: [
      { type: "docs", url: "https://docs.github.com/en/actions/learn-github-actions" },
      { type: "api", url: "https://docs.github.com/en/rest/actions" },
      { type: "github", url: "https://github.com/actions/toolkit" },
    ],
  },
  {
    name: "Terraform",
    slug: "terraform",
    description: "Infrastructure as code tool to provision and manage cloud resources",
    npm_package: undefined,
    github_repo: "hashicorp/terraform",
    docs_url: "https://developer.hashicorp.com/terraform/docs",
    tags: ["devops", "infra-as-code", "cloud"],
    links: [
      { type: "docs", url: "https://developer.hashicorp.com/terraform/docs" },
      { type: "api", url: "https://developer.hashicorp.com/terraform/language" },
      { type: "github", url: "https://github.com/hashicorp/terraform" },
    ],
  },

  // ─── GraphQL ──────────────────────────────────────────────────────────────────
  {
    name: "GraphQL",
    slug: "graphql",
    description: "A query language for your API and a server-side runtime for executing queries",
    npm_package: "graphql",
    github_repo: "graphql/graphql-js",
    docs_url: "https://graphql.org/learn",
    tags: ["api", "query-language", "schema"],
    links: [
      { type: "docs", url: "https://graphql.org/learn" },
      { type: "api", url: "https://graphql.org/graphql-js" },
      { type: "npm", url: "https://npmjs.com/package/graphql" },
      { type: "github", url: "https://github.com/graphql/graphql-js" },
    ],
  },
  {
    name: "Apollo Client",
    slug: "apollo-client",
    description: "Comprehensive state management library for JavaScript that enables GraphQL",
    npm_package: "@apollo/client",
    github_repo: "apollographql/apollo-client",
    docs_url: "https://www.apollographql.com/docs/react",
    tags: ["graphql", "state-management", "react"],
    links: [
      { type: "docs", url: "https://www.apollographql.com/docs/react" },
      { type: "api", url: "https://www.apollographql.com/docs/react/api/core/ApolloClient" },
      { type: "npm", url: "https://npmjs.com/package/@apollo/client" },
      { type: "github", url: "https://github.com/apollographql/apollo-client" },
    ],
  },

  // ─── TypeScript Tools ─────────────────────────────────────────────────────────
  {
    name: "TypeScript",
    slug: "typescript",
    description: "Strongly typed programming language that builds on JavaScript",
    npm_package: "typescript",
    github_repo: "microsoft/TypeScript",
    docs_url: "https://www.typescriptlang.org/docs",
    tags: ["language", "typescript", "types"],
    links: [
      { type: "docs", url: "https://www.typescriptlang.org/docs/handbook/intro.html" },
      { type: "api", url: "https://www.typescriptlang.org/tsconfig" },
      { type: "npm", url: "https://npmjs.com/package/typescript" },
      { type: "github", url: "https://github.com/microsoft/TypeScript" },
    ],
  },
  {
    name: "ESLint",
    slug: "eslint",
    description: "Find and fix problems in your JavaScript/TypeScript code",
    npm_package: "eslint",
    github_repo: "eslint/eslint",
    docs_url: "https://eslint.org/docs",
    tags: ["tooling", "linting", "javascript", "typescript"],
    links: [
      { type: "docs", url: "https://eslint.org/docs/latest/use/getting-started" },
      { type: "api", url: "https://eslint.org/docs/latest/use/core-concepts" },
      { type: "npm", url: "https://npmjs.com/package/eslint" },
      { type: "github", url: "https://github.com/eslint/eslint" },
    ],
  },
  {
    name: "Prettier",
    slug: "prettier",
    description: "An opinionated code formatter for JavaScript, TypeScript, CSS, and more",
    npm_package: "prettier",
    github_repo: "prettier/prettier",
    docs_url: "https://prettier.io/docs/en",
    tags: ["tooling", "formatting", "javascript"],
    links: [
      { type: "docs", url: "https://prettier.io/docs/en/index.html" },
      { type: "npm", url: "https://npmjs.com/package/prettier" },
      { type: "github", url: "https://github.com/prettier/prettier" },
    ],
  },
  {
    name: "Biome",
    slug: "biome",
    description: "One toolchain for your web project — linter and formatter",
    npm_package: "@biomejs/biome",
    github_repo: "biomejs/biome",
    docs_url: "https://biomejs.dev/docs",
    tags: ["tooling", "linting", "formatting", "rust"],
    links: [
      { type: "docs", url: "https://biomejs.dev/guides/getting-started" },
      { type: "api", url: "https://biomejs.dev/reference/configuration" },
      { type: "npm", url: "https://npmjs.com/package/@biomejs/biome" },
      { type: "github", url: "https://github.com/biomejs/biome" },
    ],
  },

  // ─── Search / Vector DBs ──────────────────────────────────────────────────────
  {
    name: "Exa",
    slug: "exa",
    description: "AI-powered web search API for finding and retrieving relevant content",
    npm_package: "exa-js",
    github_repo: "exa-labs/exa-js",
    docs_url: "https://docs.exa.ai",
    tags: ["search", "ai", "api", "web"],
    links: [
      { type: "docs", url: "https://docs.exa.ai/reference/getting-started" },
      { type: "api", url: "https://docs.exa.ai/reference/search-endpoint" },
      { type: "npm", url: "https://npmjs.com/package/exa-js" },
      { type: "github", url: "https://github.com/exa-labs/exa-js" },
    ],
  },
  {
    name: "Firecrawl",
    slug: "firecrawl",
    description: "Turn any website into LLM-ready data — scraping and crawling API",
    npm_package: "@mendable/firecrawl-js",
    github_repo: "mendableai/firecrawl",
    docs_url: "https://docs.firecrawl.dev",
    tags: ["scraping", "crawling", "ai", "data"],
    links: [
      { type: "docs", url: "https://docs.firecrawl.dev/introduction" },
      { type: "api", url: "https://docs.firecrawl.dev/api-reference/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@mendable/firecrawl-js" },
      { type: "github", url: "https://github.com/mendableai/firecrawl" },
    ],
  },
];
