import type { SeedLibrary } from "./types.js";

export const FRONTEND_SEED_LIBRARIES: SeedLibrary[] = [
  // ─── JavaScript / TypeScript Frameworks ──────────────────────────────────────
  {
    name: "React",
    slug: "react",
    description: "A JavaScript library for building user interfaces",
    npm_package: "react",
    github_repo: "facebook/react",
    docs_url: "https://react.dev",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://react.dev/reference/react" },
      { type: "npm", url: "https://npmjs.com/package/react" },
      { type: "github", url: "https://github.com/facebook/react" },
      { type: "changelog", url: "https://github.com/facebook/react/blob/main/CHANGELOG.md" },
    ],
  },
  {
    name: "Vue",
    slug: "vue",
    description: "Progressive JavaScript framework for building UIs",
    npm_package: "vue",
    github_repo: "vuejs/core",
    docs_url: "https://vuejs.org",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://vuejs.org/guide/introduction.html" },
      { type: "api", url: "https://vuejs.org/api/" },
      { type: "npm", url: "https://npmjs.com/package/vue" },
      { type: "github", url: "https://github.com/vuejs/core" },
    ],
  },
  {
    name: "Angular",
    slug: "angular",
    description: "Platform for building mobile and desktop web applications",
    npm_package: "@angular/core",
    github_repo: "angular/angular",
    docs_url: "https://angular.dev",
    tags: ["javascript", "typescript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://angular.dev/overview" },
      { type: "api", url: "https://angular.dev/api" },
      { type: "npm", url: "https://npmjs.com/package/@angular/core" },
      { type: "github", url: "https://github.com/angular/angular" },
    ],
  },
  {
    name: "Svelte",
    slug: "svelte",
    description: "Cybernetically enhanced web apps with zero runtime overhead",
    npm_package: "svelte",
    github_repo: "sveltejs/svelte",
    docs_url: "https://svelte.dev/docs",
    tags: ["javascript", "ui", "frontend", "framework", "compiler"],
    links: [
      { type: "docs", url: "https://svelte.dev/docs" },
      { type: "npm", url: "https://npmjs.com/package/svelte" },
      { type: "github", url: "https://github.com/sveltejs/svelte" },
    ],
  },
  {
    name: "SolidJS",
    slug: "solid",
    description: "Simple and performant reactivity for building user interfaces",
    npm_package: "solid-js",
    github_repo: "solidjs/solid",
    docs_url: "https://docs.solidjs.com",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://docs.solidjs.com" },
      { type: "npm", url: "https://npmjs.com/package/solid-js" },
      { type: "github", url: "https://github.com/solidjs/solid" },
    ],
  },
  {
    name: "Preact",
    slug: "preact",
    description: "Fast 3kB alternative to React with the same modern API",
    npm_package: "preact",
    github_repo: "preactjs/preact",
    docs_url: "https://preactjs.com/guide/v10/getting-started",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://preactjs.com" },
      { type: "npm", url: "https://npmjs.com/package/preact" },
      { type: "github", url: "https://github.com/preactjs/preact" },
    ],
  },

  // ─── Meta-frameworks ──────────────────────────────────────────────────────────
  {
    name: "Next.js",
    slug: "nextjs",
    description: "The React framework for the web — production-ready with SSR, SSG, and RSC",
    npm_package: "next",
    github_repo: "vercel/next.js",
    docs_url: "https://nextjs.org/docs",
    tags: ["javascript", "react", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://nextjs.org/docs" },
      { type: "api", url: "https://nextjs.org/docs/app/api-reference" },
      { type: "npm", url: "https://npmjs.com/package/next" },
      { type: "github", url: "https://github.com/vercel/next.js" },
    ],
  },
  {
    name: "Nuxt",
    slug: "nuxt",
    description: "The intuitive Vue framework — SSR/SSG with powerful conventions",
    npm_package: "nuxt",
    github_repo: "nuxt/nuxt",
    docs_url: "https://nuxt.com/docs",
    tags: ["javascript", "vue", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://nuxt.com/docs/getting-started/introduction" },
      { type: "api", url: "https://nuxt.com/docs/api" },
      { type: "npm", url: "https://npmjs.com/package/nuxt" },
      { type: "github", url: "https://github.com/nuxt/nuxt" },
    ],
  },
  {
    name: "Remix",
    slug: "remix",
    description: "Full stack web framework focused on web fundamentals",
    npm_package: "@remix-run/node",
    github_repo: "remix-run/remix",
    docs_url: "https://remix.run/docs",
    tags: ["javascript", "react", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://remix.run/docs/en/main" },
      { type: "npm", url: "https://npmjs.com/package/@remix-run/node" },
      { type: "github", url: "https://github.com/remix-run/remix" },
    ],
  },
  {
    name: "Astro",
    slug: "astro",
    description: "Build fast websites with any UI framework — zero JS by default",
    npm_package: "astro",
    github_repo: "withastro/astro",
    docs_url: "https://docs.astro.build",
    tags: ["javascript", "framework", "static-site", "island-architecture"],
    links: [
      { type: "docs", url: "https://docs.astro.build" },
      { type: "api", url: "https://docs.astro.build/en/reference/api-reference/" },
      { type: "npm", url: "https://npmjs.com/package/astro" },
      { type: "github", url: "https://github.com/withastro/astro" },
    ],
  },
  {
    name: "SvelteKit",
    slug: "sveltekit",
    description: "Web application framework powered by Svelte",
    npm_package: "@sveltejs/kit",
    github_repo: "sveltejs/kit",
    docs_url: "https://kit.svelte.dev/docs",
    tags: ["javascript", "svelte", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://kit.svelte.dev/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@sveltejs/kit" },
      { type: "github", url: "https://github.com/sveltejs/kit" },
    ],
  },

  // ─── Node.js / Bun server frameworks ─────────────────────────────────────────
  {
    name: "Express",
    slug: "express",
    description: "Fast, unopinionated, minimalist web framework for Node.js",
    npm_package: "express",
    github_repo: "expressjs/express",
    docs_url: "https://expressjs.com",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://expressjs.com/en/4x/api.html" },
      { type: "npm", url: "https://npmjs.com/package/express" },
      { type: "github", url: "https://github.com/expressjs/express" },
    ],
  },
  {
    name: "Fastify",
    slug: "fastify",
    description: "Fast and low overhead web framework for Node.js",
    npm_package: "fastify",
    github_repo: "fastify/fastify",
    docs_url: "https://fastify.dev/docs",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://fastify.dev/docs/latest" },
      { type: "npm", url: "https://npmjs.com/package/fastify" },
      { type: "github", url: "https://github.com/fastify/fastify" },
    ],
  },
  {
    name: "Hono",
    slug: "hono",
    description: "Ultrafast web framework for the Edges — Cloudflare Workers, Bun, Deno, Node.js",
    npm_package: "hono",
    github_repo: "honojs/hono",
    docs_url: "https://hono.dev/docs",
    tags: ["javascript", "server", "framework", "edge", "bun", "cloudflare"],
    links: [
      { type: "docs", url: "https://hono.dev/docs" },
      { type: "npm", url: "https://npmjs.com/package/hono" },
      { type: "github", url: "https://github.com/honojs/hono" },
    ],
  },
  {
    name: "Koa",
    slug: "koa",
    description: "Next generation web framework for Node.js by the Express team",
    npm_package: "koa",
    github_repo: "koajs/koa",
    docs_url: "https://koajs.com",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://koajs.com" },
      { type: "npm", url: "https://npmjs.com/package/koa" },
      { type: "github", url: "https://github.com/koajs/koa" },
    ],
  },
  {
    name: "tRPC",
    slug: "trpc",
    description: "End-to-end typesafe APIs made easy — no codegen, no schema",
    npm_package: "@trpc/server",
    github_repo: "trpc/trpc",
    docs_url: "https://trpc.io/docs",
    tags: ["typescript", "api", "rpc", "fullstack", "typesafe"],
    links: [
      { type: "docs", url: "https://trpc.io/docs/quickstart" },
      { type: "npm", url: "https://npmjs.com/package/@trpc/server" },
      { type: "github", url: "https://github.com/trpc/trpc" },
    ],
  },
  {
    name: "Elysia",
    slug: "elysia",
    description: "Ergonomic web framework for Bun with end-to-end type safety",
    npm_package: "elysia",
    github_repo: "elysiajs/elysia",
    docs_url: "https://elysiajs.com/quick-start.html",
    tags: ["typescript", "bun", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://elysiajs.com" },
      { type: "npm", url: "https://npmjs.com/package/elysia" },
      { type: "github", url: "https://github.com/elysiajs/elysia" },
    ],
  },

  // ─── State Management ─────────────────────────────────────────────────────────
  {
    name: "Redux Toolkit",
    slug: "redux-toolkit",
    description: "The official, opinionated toolset for efficient Redux development",
    npm_package: "@reduxjs/toolkit",
    github_repo: "reduxjs/redux-toolkit",
    docs_url: "https://redux-toolkit.js.org",
    tags: ["javascript", "state-management", "react"],
    links: [
      { type: "docs", url: "https://redux-toolkit.js.org/introduction/getting-started" },
      { type: "api", url: "https://redux-toolkit.js.org/api/configureStore" },
      { type: "npm", url: "https://npmjs.com/package/@reduxjs/toolkit" },
      { type: "github", url: "https://github.com/reduxjs/redux-toolkit" },
    ],
  },
  {
    name: "Zustand",
    slug: "zustand",
    description: "A small, fast, and scalable state management solution for React",
    npm_package: "zustand",
    github_repo: "pmndrs/zustand",
    docs_url: "https://docs.pmnd.rs/zustand",
    tags: ["javascript", "state-management", "react"],
    links: [
      { type: "docs", url: "https://docs.pmnd.rs/zustand/getting-started/introduction" },
      { type: "npm", url: "https://npmjs.com/package/zustand" },
      { type: "github", url: "https://github.com/pmndrs/zustand" },
    ],
  },
  {
    name: "Jotai",
    slug: "jotai",
    description: "Primitive and flexible state management for React",
    npm_package: "jotai",
    github_repo: "pmndrs/jotai",
    docs_url: "https://jotai.org/docs/introduction",
    tags: ["javascript", "state-management", "react", "atomic"],
    links: [
      { type: "docs", url: "https://jotai.org/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/jotai" },
      { type: "github", url: "https://github.com/pmndrs/jotai" },
    ],
  },
  {
    name: "MobX",
    slug: "mobx",
    description: "Simple, scalable state management through transparent reactive programming",
    npm_package: "mobx",
    github_repo: "mobxjs/mobx",
    docs_url: "https://mobx.js.org/README.html",
    tags: ["javascript", "state-management", "reactive"],
    links: [
      { type: "docs", url: "https://mobx.js.org/README.html" },
      { type: "npm", url: "https://npmjs.com/package/mobx" },
      { type: "github", url: "https://github.com/mobxjs/mobx" },
    ],
  },
  {
    name: "XState",
    slug: "xstate",
    description: "State machines and statecharts for the modern web",
    npm_package: "xstate",
    github_repo: "statelyai/xstate",
    docs_url: "https://stately.ai/docs",
    tags: ["javascript", "state-management", "state-machine"],
    links: [
      { type: "docs", url: "https://stately.ai/docs/xstate" },
      { type: "npm", url: "https://npmjs.com/package/xstate" },
      { type: "github", url: "https://github.com/statelyai/xstate" },
    ],
  },
  {
    name: "TanStack Query",
    slug: "tanstack-query",
    description: "Powerful asynchronous state management and data fetching for TypeScript/JS",
    npm_package: "@tanstack/react-query",
    github_repo: "TanStack/query",
    docs_url: "https://tanstack.com/query/latest/docs",
    tags: ["javascript", "state-management", "data-fetching", "react"],
    links: [
      { type: "docs", url: "https://tanstack.com/query/latest/docs/framework/react/overview" },
      { type: "npm", url: "https://npmjs.com/package/@tanstack/react-query" },
      { type: "github", url: "https://github.com/TanStack/query" },
    ],
  },

  // ─── Testing ──────────────────────────────────────────────────────────────────
  {
    name: "Vitest",
    slug: "vitest",
    description: "Next generation testing framework powered by Vite",
    npm_package: "vitest",
    github_repo: "vitest-dev/vitest",
    docs_url: "https://vitest.dev/guide",
    tags: ["javascript", "testing", "unit-test"],
    links: [
      { type: "docs", url: "https://vitest.dev/guide" },
      { type: "api", url: "https://vitest.dev/api" },
      { type: "npm", url: "https://npmjs.com/package/vitest" },
      { type: "github", url: "https://github.com/vitest-dev/vitest" },
    ],
  },
  {
    name: "Jest",
    slug: "jest",
    description: "Delightful JavaScript testing framework with a focus on simplicity",
    npm_package: "jest",
    github_repo: "jestjs/jest",
    docs_url: "https://jestjs.io/docs/getting-started",
    tags: ["javascript", "testing", "unit-test"],
    links: [
      { type: "docs", url: "https://jestjs.io/docs/getting-started" },
      { type: "api", url: "https://jestjs.io/docs/api" },
      { type: "npm", url: "https://npmjs.com/package/jest" },
      { type: "github", url: "https://github.com/jestjs/jest" },
    ],
  },
  {
    name: "Playwright",
    slug: "playwright",
    description: "Reliable end-to-end testing for modern web apps",
    npm_package: "@playwright/test",
    github_repo: "microsoft/playwright",
    docs_url: "https://playwright.dev/docs/intro",
    tags: ["javascript", "testing", "e2e", "browser"],
    links: [
      { type: "docs", url: "https://playwright.dev/docs/intro" },
      { type: "api", url: "https://playwright.dev/docs/api/class-playwright" },
      { type: "npm", url: "https://npmjs.com/package/@playwright/test" },
      { type: "github", url: "https://github.com/microsoft/playwright" },
    ],
  },
  {
    name: "Cypress",
    slug: "cypress",
    description: "Fast, easy and reliable testing for anything that runs in a browser",
    npm_package: "cypress",
    github_repo: "cypress-io/cypress",
    docs_url: "https://docs.cypress.io",
    tags: ["javascript", "testing", "e2e", "browser"],
    links: [
      { type: "docs", url: "https://docs.cypress.io/guides/overview/why-cypress" },
      { type: "api", url: "https://docs.cypress.io/api/table-of-contents" },
      { type: "npm", url: "https://npmjs.com/package/cypress" },
      { type: "github", url: "https://github.com/cypress-io/cypress" },
    ],
  },
  {
    name: "Testing Library",
    slug: "testing-library",
    description: "Simple and complete testing utilities that encourage good practices",
    npm_package: "@testing-library/react",
    github_repo: "testing-library/react-testing-library",
    docs_url: "https://testing-library.com/docs",
    tags: ["javascript", "testing", "react", "dom"],
    links: [
      { type: "docs", url: "https://testing-library.com/docs/react-testing-library/intro" },
      { type: "npm", url: "https://npmjs.com/package/@testing-library/react" },
      { type: "github", url: "https://github.com/testing-library/react-testing-library" },
    ],
  },

  // ─── Build Tools ──────────────────────────────────────────────────────────────
  {
    name: "Vite",
    slug: "vite",
    description: "Next generation frontend tooling — fast dev server and optimized builds",
    npm_package: "vite",
    github_repo: "vitejs/vite",
    docs_url: "https://vitejs.dev/guide",
    tags: ["javascript", "build-tool", "bundler", "dev-server"],
    links: [
      { type: "docs", url: "https://vitejs.dev/guide" },
      { type: "api", url: "https://vitejs.dev/guide/api-javascript" },
      { type: "npm", url: "https://npmjs.com/package/vite" },
      { type: "github", url: "https://github.com/vitejs/vite" },
    ],
  },
  {
    name: "esbuild",
    slug: "esbuild",
    description: "An extremely fast JavaScript bundler and minifier",
    npm_package: "esbuild",
    github_repo: "evanw/esbuild",
    docs_url: "https://esbuild.github.io",
    tags: ["javascript", "build-tool", "bundler"],
    links: [
      { type: "docs", url: "https://esbuild.github.io/api" },
      { type: "npm", url: "https://npmjs.com/package/esbuild" },
      { type: "github", url: "https://github.com/evanw/esbuild" },
    ],
  },
  {
    name: "Webpack",
    slug: "webpack",
    description: "A static module bundler for modern JavaScript applications",
    npm_package: "webpack",
    github_repo: "webpack/webpack",
    docs_url: "https://webpack.js.org/concepts",
    tags: ["javascript", "build-tool", "bundler"],
    links: [
      { type: "docs", url: "https://webpack.js.org/concepts" },
      { type: "api", url: "https://webpack.js.org/api" },
      { type: "npm", url: "https://npmjs.com/package/webpack" },
      { type: "github", url: "https://github.com/webpack/webpack" },
    ],
  },
  {
    name: "Rollup",
    slug: "rollup",
    description: "Module bundler for JavaScript — optimized for ES modules",
    npm_package: "rollup",
    github_repo: "rollup/rollup",
    docs_url: "https://rollupjs.org/guide",
    tags: ["javascript", "build-tool", "bundler", "esm"],
    links: [
      { type: "docs", url: "https://rollupjs.org/guide/en" },
      { type: "npm", url: "https://npmjs.com/package/rollup" },
      { type: "github", url: "https://github.com/rollup/rollup" },
    ],
  },
  {
    name: "Turbopack",
    slug: "turbopack",
    description: "Incremental bundler and build system optimized for JavaScript and TypeScript",
    npm_package: "turbopack",
    github_repo: "vercel/turbo",
    docs_url: "https://turbo.build/pack/docs",
    tags: ["javascript", "build-tool", "bundler", "rust"],
    links: [
      { type: "docs", url: "https://turbo.build/pack/docs" },
      { type: "github", url: "https://github.com/vercel/turbo" },
    ],
  },

  // ─── CSS / Styling ────────────────────────────────────────────────────────────
  {
    name: "Tailwind CSS",
    slug: "tailwindcss",
    description: "Utility-first CSS framework for rapidly building custom designs",
    npm_package: "tailwindcss",
    github_repo: "tailwindlabs/tailwindcss",
    docs_url: "https://tailwindcss.com/docs",
    tags: ["css", "styling", "utility-first"],
    links: [
      { type: "docs", url: "https://tailwindcss.com/docs/installation" },
      { type: "npm", url: "https://npmjs.com/package/tailwindcss" },
      { type: "github", url: "https://github.com/tailwindlabs/tailwindcss" },
    ],
  },
  {
    name: "shadcn/ui",
    slug: "shadcn-ui",
    description: "Beautifully designed React components built with Radix UI and Tailwind CSS",
    npm_package: "shadcn-ui",
    github_repo: "shadcn-ui/ui",
    docs_url: "https://ui.shadcn.com/docs",
    tags: ["css", "ui", "react", "radix", "tailwind"],
    links: [
      { type: "docs", url: "https://ui.shadcn.com/docs/introduction" },
      { type: "github", url: "https://github.com/shadcn-ui/ui" },
    ],
  },
  {
    name: "Radix UI",
    slug: "radix-ui",
    description: "Unstyled, accessible React component primitives",
    npm_package: "@radix-ui/react-dialog",
    github_repo: "radix-ui/primitives",
    docs_url: "https://www.radix-ui.com/primitives/docs/overview/introduction",
    tags: ["css", "ui", "react", "accessibility", "headless"],
    links: [
      { type: "docs", url: "https://www.radix-ui.com/primitives/docs" },
      { type: "npm", url: "https://npmjs.com/package/@radix-ui/react-dialog" },
      { type: "github", url: "https://github.com/radix-ui/primitives" },
    ],
  },
  {
    name: "Styled Components",
    slug: "styled-components",
    description: "CSS-in-JS library for styling React components",
    npm_package: "styled-components",
    github_repo: "styled-components/styled-components",
    docs_url: "https://styled-components.com/docs",
    tags: ["css", "css-in-js", "react"],
    links: [
      { type: "docs", url: "https://styled-components.com/docs" },
      { type: "npm", url: "https://npmjs.com/package/styled-components" },
      { type: "github", url: "https://github.com/styled-components/styled-components" },
    ],
  },
  {
    name: "Framer Motion",
    slug: "framer-motion",
    description: "A production-ready motion library for React",
    npm_package: "framer-motion",
    github_repo: "framer/motion",
    docs_url: "https://www.framer.com/motion",
    tags: ["css", "animation", "react"],
    links: [
      { type: "docs", url: "https://www.framer.com/motion/introduction" },
      { type: "api", url: "https://www.framer.com/motion/animation" },
      { type: "npm", url: "https://npmjs.com/package/framer-motion" },
      { type: "github", url: "https://github.com/framer/motion" },
    ],
  },
];
