export interface SeedLibrary {
  name: string;
  slug: string;
  description: string;
  npm_package?: string;
  github_repo?: string;
  docs_url?: string;
  tags: string[];
  links?: Array<{ type: string; url: string; label?: string }>;
}

export const SEED_LIBRARIES: SeedLibrary[] = [
  // ─── JavaScript / TypeScript Frameworks ──────────────────────────────────────
  {
    name: "React",
    slug: "react",
    description: "A JavaScript library for building user interfaces",
    npm_package: "react",
    github_repo: "facebook/react",
    docs_url: "https://react.dev",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://react.dev/reference/react" },
      { type: "npm", url: "https://npmjs.com/package/react" },
      { type: "github", url: "https://github.com/facebook/react" },
      { type: "changelog", url: "https://github.com/facebook/react/blob/main/CHANGELOG.md" },
    ],
  },
  {
    name: "Vue",
    slug: "vue",
    description: "Progressive JavaScript framework for building UIs",
    npm_package: "vue",
    github_repo: "vuejs/core",
    docs_url: "https://vuejs.org",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://vuejs.org/guide/introduction.html" },
      { type: "api", url: "https://vuejs.org/api/" },
      { type: "npm", url: "https://npmjs.com/package/vue" },
      { type: "github", url: "https://github.com/vuejs/core" },
    ],
  },
  {
    name: "Angular",
    slug: "angular",
    description: "Platform for building mobile and desktop web applications",
    npm_package: "@angular/core",
    github_repo: "angular/angular",
    docs_url: "https://angular.dev",
    tags: ["javascript", "typescript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://angular.dev/overview" },
      { type: "api", url: "https://angular.dev/api" },
      { type: "npm", url: "https://npmjs.com/package/@angular/core" },
      { type: "github", url: "https://github.com/angular/angular" },
    ],
  },
  {
    name: "Svelte",
    slug: "svelte",
    description: "Cybernetically enhanced web apps with zero runtime overhead",
    npm_package: "svelte",
    github_repo: "sveltejs/svelte",
    docs_url: "https://svelte.dev/docs",
    tags: ["javascript", "ui", "frontend", "framework", "compiler"],
    links: [
      { type: "docs", url: "https://svelte.dev/docs" },
      { type: "npm", url: "https://npmjs.com/package/svelte" },
      { type: "github", url: "https://github.com/sveltejs/svelte" },
    ],
  },
  {
    name: "SolidJS",
    slug: "solid",
    description: "Simple and performant reactivity for building user interfaces",
    npm_package: "solid-js",
    github_repo: "solidjs/solid",
    docs_url: "https://docs.solidjs.com",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://docs.solidjs.com" },
      { type: "npm", url: "https://npmjs.com/package/solid-js" },
      { type: "github", url: "https://github.com/solidjs/solid" },
    ],
  },
  {
    name: "Preact",
    slug: "preact",
    description: "Fast 3kB alternative to React with the same modern API",
    npm_package: "preact",
    github_repo: "preactjs/preact",
    docs_url: "https://preactjs.com/guide/v10/getting-started",
    tags: ["javascript", "ui", "frontend", "framework"],
    links: [
      { type: "docs", url: "https://preactjs.com" },
      { type: "npm", url: "https://npmjs.com/package/preact" },
      { type: "github", url: "https://github.com/preactjs/preact" },
    ],
  },

  // ─── Meta-frameworks ──────────────────────────────────────────────────────────
  {
    name: "Next.js",
    slug: "nextjs",
    description: "The React framework for the web — production-ready with SSR, SSG, and RSC",
    npm_package: "next",
    github_repo: "vercel/next.js",
    docs_url: "https://nextjs.org/docs",
    tags: ["javascript", "react", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://nextjs.org/docs" },
      { type: "api", url: "https://nextjs.org/docs/app/api-reference" },
      { type: "npm", url: "https://npmjs.com/package/next" },
      { type: "github", url: "https://github.com/vercel/next.js" },
    ],
  },
  {
    name: "Nuxt",
    slug: "nuxt",
    description: "The intuitive Vue framework — SSR/SSG with powerful conventions",
    npm_package: "nuxt",
    github_repo: "nuxt/nuxt",
    docs_url: "https://nuxt.com/docs",
    tags: ["javascript", "vue", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://nuxt.com/docs/getting-started/introduction" },
      { type: "api", url: "https://nuxt.com/docs/api" },
      { type: "npm", url: "https://npmjs.com/package/nuxt" },
      { type: "github", url: "https://github.com/nuxt/nuxt" },
    ],
  },
  {
    name: "Remix",
    slug: "remix",
    description: "Full stack web framework focused on web fundamentals",
    npm_package: "@remix-run/node",
    github_repo: "remix-run/remix",
    docs_url: "https://remix.run/docs",
    tags: ["javascript", "react", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://remix.run/docs/en/main" },
      { type: "npm", url: "https://npmjs.com/package/@remix-run/node" },
      { type: "github", url: "https://github.com/remix-run/remix" },
    ],
  },
  {
    name: "Astro",
    slug: "astro",
    description: "Build fast websites with any UI framework — zero JS by default",
    npm_package: "astro",
    github_repo: "withastro/astro",
    docs_url: "https://docs.astro.build",
    tags: ["javascript", "framework", "static-site", "island-architecture"],
    links: [
      { type: "docs", url: "https://docs.astro.build" },
      { type: "api", url: "https://docs.astro.build/en/reference/api-reference/" },
      { type: "npm", url: "https://npmjs.com/package/astro" },
      { type: "github", url: "https://github.com/withastro/astro" },
    ],
  },
  {
    name: "SvelteKit",
    slug: "sveltekit",
    description: "Web application framework powered by Svelte",
    npm_package: "@sveltejs/kit",
    github_repo: "sveltejs/kit",
    docs_url: "https://kit.svelte.dev/docs",
    tags: ["javascript", "svelte", "framework", "ssr", "fullstack"],
    links: [
      { type: "docs", url: "https://kit.svelte.dev/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@sveltejs/kit" },
      { type: "github", url: "https://github.com/sveltejs/kit" },
    ],
  },

  // ─── Node.js / Bun server frameworks ─────────────────────────────────────────
  {
    name: "Express",
    slug: "express",
    description: "Fast, unopinionated, minimalist web framework for Node.js",
    npm_package: "express",
    github_repo: "expressjs/express",
    docs_url: "https://expressjs.com",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://expressjs.com/en/4x/api.html" },
      { type: "npm", url: "https://npmjs.com/package/express" },
      { type: "github", url: "https://github.com/expressjs/express" },
    ],
  },
  {
    name: "Fastify",
    slug: "fastify",
    description: "Fast and low overhead web framework for Node.js",
    npm_package: "fastify",
    github_repo: "fastify/fastify",
    docs_url: "https://fastify.dev/docs",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://fastify.dev/docs/latest" },
      { type: "npm", url: "https://npmjs.com/package/fastify" },
      { type: "github", url: "https://github.com/fastify/fastify" },
    ],
  },
  {
    name: "Hono",
    slug: "hono",
    description: "Ultrafast web framework for the Edges — Cloudflare Workers, Bun, Deno, Node.js",
    npm_package: "hono",
    github_repo: "honojs/hono",
    docs_url: "https://hono.dev/docs",
    tags: ["javascript", "server", "framework", "edge", "bun", "cloudflare"],
    links: [
      { type: "docs", url: "https://hono.dev/docs" },
      { type: "npm", url: "https://npmjs.com/package/hono" },
      { type: "github", url: "https://github.com/honojs/hono" },
    ],
  },
  {
    name: "Koa",
    slug: "koa",
    description: "Next generation web framework for Node.js by the Express team",
    npm_package: "koa",
    github_repo: "koajs/koa",
    docs_url: "https://koajs.com",
    tags: ["javascript", "nodejs", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://koajs.com" },
      { type: "npm", url: "https://npmjs.com/package/koa" },
      { type: "github", url: "https://github.com/koajs/koa" },
    ],
  },
  {
    name: "tRPC",
    slug: "trpc",
    description: "End-to-end typesafe APIs made easy — no codegen, no schema",
    npm_package: "@trpc/server",
    github_repo: "trpc/trpc",
    docs_url: "https://trpc.io/docs",
    tags: ["typescript", "api", "rpc", "fullstack", "typesafe"],
    links: [
      { type: "docs", url: "https://trpc.io/docs/quickstart" },
      { type: "npm", url: "https://npmjs.com/package/@trpc/server" },
      { type: "github", url: "https://github.com/trpc/trpc" },
    ],
  },
  {
    name: "Elysia",
    slug: "elysia",
    description: "Ergonomic web framework for Bun with end-to-end type safety",
    npm_package: "elysia",
    github_repo: "elysiajs/elysia",
    docs_url: "https://elysiajs.com/quick-start.html",
    tags: ["typescript", "bun", "server", "framework", "http"],
    links: [
      { type: "docs", url: "https://elysiajs.com" },
      { type: "npm", url: "https://npmjs.com/package/elysia" },
      { type: "github", url: "https://github.com/elysiajs/elysia" },
    ],
  },

  // ─── State Management ─────────────────────────────────────────────────────────
  {
    name: "Redux Toolkit",
    slug: "redux-toolkit",
    description: "The official, opinionated toolset for efficient Redux development",
    npm_package: "@reduxjs/toolkit",
    github_repo: "reduxjs/redux-toolkit",
    docs_url: "https://redux-toolkit.js.org",
    tags: ["javascript", "state-management", "react"],
    links: [
      { type: "docs", url: "https://redux-toolkit.js.org/introduction/getting-started" },
      { type: "api", url: "https://redux-toolkit.js.org/api/configureStore" },
      { type: "npm", url: "https://npmjs.com/package/@reduxjs/toolkit" },
      { type: "github", url: "https://github.com/reduxjs/redux-toolkit" },
    ],
  },
  {
    name: "Zustand",
    slug: "zustand",
    description: "A small, fast, and scalable state management solution for React",
    npm_package: "zustand",
    github_repo: "pmndrs/zustand",
    docs_url: "https://docs.pmnd.rs/zustand",
    tags: ["javascript", "state-management", "react"],
    links: [
      { type: "docs", url: "https://docs.pmnd.rs/zustand/getting-started/introduction" },
      { type: "npm", url: "https://npmjs.com/package/zustand" },
      { type: "github", url: "https://github.com/pmndrs/zustand" },
    ],
  },
  {
    name: "Jotai",
    slug: "jotai",
    description: "Primitive and flexible state management for React",
    npm_package: "jotai",
    github_repo: "pmndrs/jotai",
    docs_url: "https://jotai.org/docs/introduction",
    tags: ["javascript", "state-management", "react", "atomic"],
    links: [
      { type: "docs", url: "https://jotai.org/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/jotai" },
      { type: "github", url: "https://github.com/pmndrs/jotai" },
    ],
  },
  {
    name: "MobX",
    slug: "mobx",
    description: "Simple, scalable state management through transparent reactive programming",
    npm_package: "mobx",
    github_repo: "mobxjs/mobx",
    docs_url: "https://mobx.js.org/README.html",
    tags: ["javascript", "state-management", "reactive"],
    links: [
      { type: "docs", url: "https://mobx.js.org/README.html" },
      { type: "npm", url: "https://npmjs.com/package/mobx" },
      { type: "github", url: "https://github.com/mobxjs/mobx" },
    ],
  },
  {
    name: "XState",
    slug: "xstate",
    description: "State machines and statecharts for the modern web",
    npm_package: "xstate",
    github_repo: "statelyai/xstate",
    docs_url: "https://stately.ai/docs",
    tags: ["javascript", "state-management", "state-machine"],
    links: [
      { type: "docs", url: "https://stately.ai/docs/xstate" },
      { type: "npm", url: "https://npmjs.com/package/xstate" },
      { type: "github", url: "https://github.com/statelyai/xstate" },
    ],
  },
  {
    name: "TanStack Query",
    slug: "tanstack-query",
    description: "Powerful asynchronous state management and data fetching for TypeScript/JS",
    npm_package: "@tanstack/react-query",
    github_repo: "TanStack/query",
    docs_url: "https://tanstack.com/query/latest/docs",
    tags: ["javascript", "state-management", "data-fetching", "react"],
    links: [
      { type: "docs", url: "https://tanstack.com/query/latest/docs/framework/react/overview" },
      { type: "npm", url: "https://npmjs.com/package/@tanstack/react-query" },
      { type: "github", url: "https://github.com/TanStack/query" },
    ],
  },

  // ─── Testing ──────────────────────────────────────────────────────────────────
  {
    name: "Vitest",
    slug: "vitest",
    description: "Next generation testing framework powered by Vite",
    npm_package: "vitest",
    github_repo: "vitest-dev/vitest",
    docs_url: "https://vitest.dev/guide",
    tags: ["javascript", "testing", "unit-test"],
    links: [
      { type: "docs", url: "https://vitest.dev/guide" },
      { type: "api", url: "https://vitest.dev/api" },
      { type: "npm", url: "https://npmjs.com/package/vitest" },
      { type: "github", url: "https://github.com/vitest-dev/vitest" },
    ],
  },
  {
    name: "Jest",
    slug: "jest",
    description: "Delightful JavaScript testing framework with a focus on simplicity",
    npm_package: "jest",
    github_repo: "jestjs/jest",
    docs_url: "https://jestjs.io/docs/getting-started",
    tags: ["javascript", "testing", "unit-test"],
    links: [
      { type: "docs", url: "https://jestjs.io/docs/getting-started" },
      { type: "api", url: "https://jestjs.io/docs/api" },
      { type: "npm", url: "https://npmjs.com/package/jest" },
      { type: "github", url: "https://github.com/jestjs/jest" },
    ],
  },
  {
    name: "Playwright",
    slug: "playwright",
    description: "Reliable end-to-end testing for modern web apps",
    npm_package: "@playwright/test",
    github_repo: "microsoft/playwright",
    docs_url: "https://playwright.dev/docs/intro",
    tags: ["javascript", "testing", "e2e", "browser"],
    links: [
      { type: "docs", url: "https://playwright.dev/docs/intro" },
      { type: "api", url: "https://playwright.dev/docs/api/class-playwright" },
      { type: "npm", url: "https://npmjs.com/package/@playwright/test" },
      { type: "github", url: "https://github.com/microsoft/playwright" },
    ],
  },
  {
    name: "Cypress",
    slug: "cypress",
    description: "Fast, easy and reliable testing for anything that runs in a browser",
    npm_package: "cypress",
    github_repo: "cypress-io/cypress",
    docs_url: "https://docs.cypress.io",
    tags: ["javascript", "testing", "e2e", "browser"],
    links: [
      { type: "docs", url: "https://docs.cypress.io/guides/overview/why-cypress" },
      { type: "api", url: "https://docs.cypress.io/api/table-of-contents" },
      { type: "npm", url: "https://npmjs.com/package/cypress" },
      { type: "github", url: "https://github.com/cypress-io/cypress" },
    ],
  },
  {
    name: "Testing Library",
    slug: "testing-library",
    description: "Simple and complete testing utilities that encourage good practices",
    npm_package: "@testing-library/react",
    github_repo: "testing-library/react-testing-library",
    docs_url: "https://testing-library.com/docs",
    tags: ["javascript", "testing", "react", "dom"],
    links: [
      { type: "docs", url: "https://testing-library.com/docs/react-testing-library/intro" },
      { type: "npm", url: "https://npmjs.com/package/@testing-library/react" },
      { type: "github", url: "https://github.com/testing-library/react-testing-library" },
    ],
  },

  // ─── Build Tools ──────────────────────────────────────────────────────────────
  {
    name: "Vite",
    slug: "vite",
    description: "Next generation frontend tooling — fast dev server and optimized builds",
    npm_package: "vite",
    github_repo: "vitejs/vite",
    docs_url: "https://vitejs.dev/guide",
    tags: ["javascript", "build-tool", "bundler", "dev-server"],
    links: [
      { type: "docs", url: "https://vitejs.dev/guide" },
      { type: "api", url: "https://vitejs.dev/guide/api-javascript" },
      { type: "npm", url: "https://npmjs.com/package/vite" },
      { type: "github", url: "https://github.com/vitejs/vite" },
    ],
  },
  {
    name: "esbuild",
    slug: "esbuild",
    description: "An extremely fast JavaScript bundler and minifier",
    npm_package: "esbuild",
    github_repo: "evanw/esbuild",
    docs_url: "https://esbuild.github.io",
    tags: ["javascript", "build-tool", "bundler"],
    links: [
      { type: "docs", url: "https://esbuild.github.io/api" },
      { type: "npm", url: "https://npmjs.com/package/esbuild" },
      { type: "github", url: "https://github.com/evanw/esbuild" },
    ],
  },
  {
    name: "Webpack",
    slug: "webpack",
    description: "A static module bundler for modern JavaScript applications",
    npm_package: "webpack",
    github_repo: "webpack/webpack",
    docs_url: "https://webpack.js.org/concepts",
    tags: ["javascript", "build-tool", "bundler"],
    links: [
      { type: "docs", url: "https://webpack.js.org/concepts" },
      { type: "api", url: "https://webpack.js.org/api" },
      { type: "npm", url: "https://npmjs.com/package/webpack" },
      { type: "github", url: "https://github.com/webpack/webpack" },
    ],
  },
  {
    name: "Rollup",
    slug: "rollup",
    description: "Module bundler for JavaScript — optimized for ES modules",
    npm_package: "rollup",
    github_repo: "rollup/rollup",
    docs_url: "https://rollupjs.org/guide",
    tags: ["javascript", "build-tool", "bundler", "esm"],
    links: [
      { type: "docs", url: "https://rollupjs.org/guide/en" },
      { type: "npm", url: "https://npmjs.com/package/rollup" },
      { type: "github", url: "https://github.com/rollup/rollup" },
    ],
  },
  {
    name: "Turbopack",
    slug: "turbopack",
    description: "Incremental bundler and build system optimized for JavaScript and TypeScript",
    npm_package: "turbopack",
    github_repo: "vercel/turbo",
    docs_url: "https://turbo.build/pack/docs",
    tags: ["javascript", "build-tool", "bundler", "rust"],
    links: [
      { type: "docs", url: "https://turbo.build/pack/docs" },
      { type: "github", url: "https://github.com/vercel/turbo" },
    ],
  },

  // ─── CSS / Styling ────────────────────────────────────────────────────────────
  {
    name: "Tailwind CSS",
    slug: "tailwindcss",
    description: "Utility-first CSS framework for rapidly building custom designs",
    npm_package: "tailwindcss",
    github_repo: "tailwindlabs/tailwindcss",
    docs_url: "https://tailwindcss.com/docs",
    tags: ["css", "styling", "utility-first"],
    links: [
      { type: "docs", url: "https://tailwindcss.com/docs/installation" },
      { type: "npm", url: "https://npmjs.com/package/tailwindcss" },
      { type: "github", url: "https://github.com/tailwindlabs/tailwindcss" },
    ],
  },
  {
    name: "shadcn/ui",
    slug: "shadcn-ui",
    description: "Beautifully designed React components built with Radix UI and Tailwind CSS",
    npm_package: "shadcn-ui",
    github_repo: "shadcn-ui/ui",
    docs_url: "https://ui.shadcn.com/docs",
    tags: ["css", "ui", "react", "radix", "tailwind"],
    links: [
      { type: "docs", url: "https://ui.shadcn.com/docs/introduction" },
      { type: "github", url: "https://github.com/shadcn-ui/ui" },
    ],
  },
  {
    name: "Radix UI",
    slug: "radix-ui",
    description: "Unstyled, accessible React component primitives",
    npm_package: "@radix-ui/react-dialog",
    github_repo: "radix-ui/primitives",
    docs_url: "https://www.radix-ui.com/primitives/docs/overview/introduction",
    tags: ["css", "ui", "react", "accessibility", "headless"],
    links: [
      { type: "docs", url: "https://www.radix-ui.com/primitives/docs" },
      { type: "npm", url: "https://npmjs.com/package/@radix-ui/react-dialog" },
      { type: "github", url: "https://github.com/radix-ui/primitives" },
    ],
  },
  {
    name: "Styled Components",
    slug: "styled-components",
    description: "CSS-in-JS library for styling React components",
    npm_package: "styled-components",
    github_repo: "styled-components/styled-components",
    docs_url: "https://styled-components.com/docs",
    tags: ["css", "css-in-js", "react"],
    links: [
      { type: "docs", url: "https://styled-components.com/docs" },
      { type: "npm", url: "https://npmjs.com/package/styled-components" },
      { type: "github", url: "https://github.com/styled-components/styled-components" },
    ],
  },
  {
    name: "Framer Motion",
    slug: "framer-motion",
    description: "A production-ready motion library for React",
    npm_package: "framer-motion",
    github_repo: "framer/motion",
    docs_url: "https://www.framer.com/motion",
    tags: ["css", "animation", "react"],
    links: [
      { type: "docs", url: "https://www.framer.com/motion/introduction" },
      { type: "api", url: "https://www.framer.com/motion/animation" },
      { type: "npm", url: "https://npmjs.com/package/framer-motion" },
      { type: "github", url: "https://github.com/framer/motion" },
    ],
  },

  // ─── Database / ORM ───────────────────────────────────────────────────────────
  {
    name: "Prisma",
    slug: "prisma",
    description: "Next-generation Node.js and TypeScript ORM for PostgreSQL, MySQL, SQLite",
    npm_package: "prisma",
    github_repo: "prisma/prisma",
    docs_url: "https://www.prisma.io/docs",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://www.prisma.io/docs/getting-started" },
      { type: "api", url: "https://www.prisma.io/docs/orm/reference/prisma-client-reference" },
      { type: "npm", url: "https://npmjs.com/package/prisma" },
      { type: "github", url: "https://github.com/prisma/prisma" },
    ],
  },
  {
    name: "Drizzle ORM",
    slug: "drizzle",
    description: "Headless TypeScript ORM with a SQL-like query API",
    npm_package: "drizzle-orm",
    github_repo: "drizzle-team/drizzle-orm",
    docs_url: "https://orm.drizzle.team/docs/overview",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://orm.drizzle.team/docs/overview" },
      { type: "npm", url: "https://npmjs.com/package/drizzle-orm" },
      { type: "github", url: "https://github.com/drizzle-team/drizzle-orm" },
    ],
  },
  {
    name: "TypeORM",
    slug: "typeorm",
    description: "ORM for TypeScript and JavaScript — Active Record and Data Mapper patterns",
    npm_package: "typeorm",
    github_repo: "typeorm/typeorm",
    docs_url: "https://typeorm.io",
    tags: ["database", "orm", "typescript", "sql"],
    links: [
      { type: "docs", url: "https://typeorm.io" },
      { type: "npm", url: "https://npmjs.com/package/typeorm" },
      { type: "github", url: "https://github.com/typeorm/typeorm" },
    ],
  },
  {
    name: "Mongoose",
    slug: "mongoose",
    description: "Elegant MongoDB object modeling for Node.js",
    npm_package: "mongoose",
    github_repo: "Automattic/mongoose",
    docs_url: "https://mongoosejs.com/docs",
    tags: ["database", "mongodb", "odm", "nosql"],
    links: [
      { type: "docs", url: "https://mongoosejs.com/docs/guide.html" },
      { type: "api", url: "https://mongoosejs.com/docs/api/mongoose.html" },
      { type: "npm", url: "https://npmjs.com/package/mongoose" },
      { type: "github", url: "https://github.com/Automattic/mongoose" },
    ],
  },
  {
    name: "Supabase",
    slug: "supabase",
    description: "Open source Firebase alternative — PostgreSQL, Auth, Storage, Realtime",
    npm_package: "@supabase/supabase-js",
    github_repo: "supabase/supabase",
    docs_url: "https://supabase.com/docs",
    tags: ["database", "backend-as-a-service", "postgresql", "realtime"],
    links: [
      { type: "docs", url: "https://supabase.com/docs/reference/javascript/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@supabase/supabase-js" },
      { type: "github", url: "https://github.com/supabase/supabase" },
    ],
  },
  {
    name: "Turso",
    slug: "turso",
    description: "SQLite for production — edge-native distributed database",
    npm_package: "@libsql/client",
    github_repo: "tursodatabase/turso-client-ts",
    docs_url: "https://docs.turso.tech",
    tags: ["database", "sqlite", "edge", "distributed"],
    links: [
      { type: "docs", url: "https://docs.turso.tech/sdk/ts/reference" },
      { type: "npm", url: "https://npmjs.com/package/@libsql/client" },
      { type: "github", url: "https://github.com/tursodatabase/turso-client-ts" },
    ],
  },
  {
    name: "Redis",
    slug: "redis",
    description: "In-memory data structure store — caching, pub/sub, queues",
    npm_package: "redis",
    github_repo: "redis/node-redis",
    docs_url: "https://redis.io/docs",
    tags: ["database", "cache", "nosql", "pub-sub"],
    links: [
      { type: "docs", url: "https://redis.io/docs/latest/develop/connect/clients/nodejs" },
      { type: "api", url: "https://redis.io/commands" },
      { type: "npm", url: "https://npmjs.com/package/redis" },
      { type: "github", url: "https://github.com/redis/node-redis" },
    ],
  },

  // ─── Validation / Schema ──────────────────────────────────────────────────────
  {
    name: "Zod",
    slug: "zod",
    description: "TypeScript-first schema declaration and validation library",
    npm_package: "zod",
    github_repo: "colinhacks/zod",
    docs_url: "https://zod.dev",
    tags: ["typescript", "validation", "schema"],
    links: [
      { type: "docs", url: "https://zod.dev/?id=introduction" },
      { type: "npm", url: "https://npmjs.com/package/zod" },
      { type: "github", url: "https://github.com/colinhacks/zod" },
    ],
  },
  {
    name: "Valibot",
    slug: "valibot",
    description: "The modular and type-safe schema library for validating structural data",
    npm_package: "valibot",
    github_repo: "fabian-hiller/valibot",
    docs_url: "https://valibot.dev/guides/introduction",
    tags: ["typescript", "validation", "schema"],
    links: [
      { type: "docs", url: "https://valibot.dev" },
      { type: "npm", url: "https://npmjs.com/package/valibot" },
      { type: "github", url: "https://github.com/fabian-hiller/valibot" },
    ],
  },

  // ─── HTTP / API clients ───────────────────────────────────────────────────────
  {
    name: "Axios",
    slug: "axios",
    description: "Promise-based HTTP client for the browser and Node.js",
    npm_package: "axios",
    github_repo: "axios/axios",
    docs_url: "https://axios-http.com/docs/intro",
    tags: ["http", "client", "promise"],
    links: [
      { type: "docs", url: "https://axios-http.com/docs/intro" },
      { type: "api", url: "https://axios-http.com/docs/api_intro" },
      { type: "npm", url: "https://npmjs.com/package/axios" },
      { type: "github", url: "https://github.com/axios/axios" },
    ],
  },
  {
    name: "ky",
    slug: "ky",
    description: "Tiny and elegant HTTP client based on Fetch API",
    npm_package: "ky",
    github_repo: "sindresorhus/ky",
    docs_url: "https://github.com/sindresorhus/ky",
    tags: ["http", "client", "fetch"],
    links: [
      { type: "docs", url: "https://github.com/sindresorhus/ky#readme" },
      { type: "npm", url: "https://npmjs.com/package/ky" },
      { type: "github", url: "https://github.com/sindresorhus/ky" },
    ],
  },

  // ─── Auth ─────────────────────────────────────────────────────────────────────
  {
    name: "Auth.js",
    slug: "authjs",
    description: "Authentication for the web — supports 80+ OAuth providers",
    npm_package: "next-auth",
    github_repo: "nextauthjs/next-auth",
    docs_url: "https://authjs.dev/getting-started",
    tags: ["auth", "oauth", "jwt", "session"],
    links: [
      { type: "docs", url: "https://authjs.dev" },
      { type: "api", url: "https://authjs.dev/reference/core" },
      { type: "npm", url: "https://npmjs.com/package/next-auth" },
      { type: "github", url: "https://github.com/nextauthjs/next-auth" },
    ],
  },
  {
    name: "Lucia",
    slug: "lucia",
    description: "Simple and flexible auth library for TypeScript",
    npm_package: "lucia",
    github_repo: "lucia-auth/lucia",
    docs_url: "https://lucia-auth.com",
    tags: ["auth", "session", "typescript"],
    links: [
      { type: "docs", url: "https://lucia-auth.com/getting-started" },
      { type: "npm", url: "https://npmjs.com/package/lucia" },
      { type: "github", url: "https://github.com/lucia-auth/lucia" },
    ],
  },
  {
    name: "Better Auth",
    slug: "better-auth",
    description: "The most comprehensive authentication framework for TypeScript",
    npm_package: "better-auth",
    github_repo: "better-auth/better-auth",
    docs_url: "https://www.better-auth.com/docs/introduction",
    tags: ["auth", "session", "typescript", "framework"],
    links: [
      { type: "docs", url: "https://www.better-auth.com/docs/introduction" },
      { type: "npm", url: "https://npmjs.com/package/better-auth" },
      { type: "github", url: "https://github.com/better-auth/better-auth" },
    ],
  },

  // ─── AI / ML ──────────────────────────────────────────────────────────────────
  {
    name: "Vercel AI SDK",
    slug: "vercel-ai-sdk",
    description: "Build AI-powered products with React, Svelte, Vue, and Node.js",
    npm_package: "ai",
    github_repo: "vercel/ai",
    docs_url: "https://sdk.vercel.ai/docs",
    tags: ["ai", "llm", "streaming", "typescript"],
    links: [
      { type: "docs", url: "https://sdk.vercel.ai/docs/introduction" },
      { type: "api", url: "https://sdk.vercel.ai/docs/reference" },
      { type: "npm", url: "https://npmjs.com/package/ai" },
      { type: "github", url: "https://github.com/vercel/ai" },
    ],
  },
  {
    name: "Anthropic SDK",
    slug: "anthropic",
    description: "Official TypeScript/JavaScript SDK for the Anthropic API (Claude)",
    npm_package: "@anthropic-ai/sdk",
    github_repo: "anthropics/anthropic-sdk-typescript",
    docs_url: "https://docs.anthropic.com",
    tags: ["ai", "llm", "claude", "sdk"],
    links: [
      { type: "docs", url: "https://docs.anthropic.com/en/api/getting-started" },
      { type: "api", url: "https://docs.anthropic.com/en/api/messages" },
      { type: "npm", url: "https://npmjs.com/package/@anthropic-ai/sdk" },
      { type: "github", url: "https://github.com/anthropics/anthropic-sdk-typescript" },
    ],
  },
  {
    name: "OpenAI SDK",
    slug: "openai",
    description: "Official TypeScript/JavaScript SDK for the OpenAI API",
    npm_package: "openai",
    github_repo: "openai/openai-node",
    docs_url: "https://platform.openai.com/docs",
    tags: ["ai", "llm", "gpt", "sdk"],
    links: [
      { type: "docs", url: "https://platform.openai.com/docs/api-reference" },
      { type: "npm", url: "https://npmjs.com/package/openai" },
      { type: "github", url: "https://github.com/openai/openai-node" },
    ],
  },
  {
    name: "LangChain.js",
    slug: "langchainjs",
    description: "Framework for building LLM-powered applications in TypeScript",
    npm_package: "langchain",
    github_repo: "langchain-ai/langchainjs",
    docs_url: "https://js.langchain.com/docs",
    tags: ["ai", "llm", "chains", "agents", "rag"],
    links: [
      { type: "docs", url: "https://js.langchain.com/docs/introduction" },
      { type: "api", url: "https://api.js.langchain.com" },
      { type: "npm", url: "https://npmjs.com/package/langchain" },
      { type: "github", url: "https://github.com/langchain-ai/langchainjs" },
    ],
  },
  {
    name: "Mastra",
    slug: "mastra",
    description: "TypeScript AI framework for building agents, workflows, and RAG pipelines",
    npm_package: "@mastra/core",
    github_repo: "mastra-ai/mastra",
    docs_url: "https://mastra.ai/docs",
    tags: ["ai", "agents", "workflows", "typescript"],
    links: [
      { type: "docs", url: "https://mastra.ai/docs" },
      { type: "npm", url: "https://npmjs.com/package/@mastra/core" },
      { type: "github", url: "https://github.com/mastra-ai/mastra" },
    ],
  },
  {
    name: "Model Context Protocol SDK",
    slug: "mcp-sdk",
    description: "TypeScript SDK for building MCP servers and clients",
    npm_package: "@modelcontextprotocol/sdk",
    github_repo: "modelcontextprotocol/typescript-sdk",
    docs_url: "https://modelcontextprotocol.io/docs",
    tags: ["ai", "mcp", "llm", "tools", "sdk"],
    links: [
      { type: "docs", url: "https://modelcontextprotocol.io/docs/concepts/architecture" },
      { type: "api", url: "https://modelcontextprotocol.io/docs/concepts/tools" },
      { type: "npm", url: "https://npmjs.com/package/@modelcontextprotocol/sdk" },
      { type: "github", url: "https://github.com/modelcontextprotocol/typescript-sdk" },
    ],
  },

  // ─── Cloud / Infrastructure ───────────────────────────────────────────────────
  {
    name: "AWS SDK v3",
    slug: "aws-sdk",
    description: "Modular AWS SDK for JavaScript and TypeScript",
    npm_package: "@aws-sdk/client-s3",
    github_repo: "aws/aws-sdk-js-v3",
    docs_url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest",
    tags: ["cloud", "aws", "sdk", "s3", "lambda"],
    links: [
      { type: "docs", url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest" },
      { type: "npm", url: "https://npmjs.com/package/@aws-sdk/client-s3" },
      { type: "github", url: "https://github.com/aws/aws-sdk-js-v3" },
    ],
  },
  {
    name: "Cloudflare Workers",
    slug: "cloudflare-workers",
    description: "Serverless JavaScript/TypeScript at the edge — Wrangler + Workers API",
    npm_package: "wrangler",
    github_repo: "cloudflare/workers-sdk",
    docs_url: "https://developers.cloudflare.com/workers",
    tags: ["cloud", "cloudflare", "edge", "serverless"],
    links: [
      { type: "docs", url: "https://developers.cloudflare.com/workers/get-started/guide" },
      { type: "api", url: "https://developers.cloudflare.com/workers/runtime-apis" },
      { type: "npm", url: "https://npmjs.com/package/wrangler" },
      { type: "github", url: "https://github.com/cloudflare/workers-sdk" },
    ],
  },
  {
    name: "Stripe",
    slug: "stripe",
    description: "Payment processing APIs — SDK for Node.js/TypeScript",
    npm_package: "stripe",
    github_repo: "stripe/stripe-node",
    docs_url: "https://docs.stripe.com/api",
    tags: ["payments", "api", "sdk"],
    links: [
      { type: "docs", url: "https://docs.stripe.com/api" },
      { type: "api", url: "https://docs.stripe.com/api#intro" },
      { type: "npm", url: "https://npmjs.com/package/stripe" },
      { type: "github", url: "https://github.com/stripe/stripe-node" },
    ],
  },
  {
    name: "Resend",
    slug: "resend",
    description: "Email API for developers — send transactional emails at scale",
    npm_package: "resend",
    github_repo: "resend/resend-node",
    docs_url: "https://resend.com/docs",
    tags: ["email", "api", "transactional"],
    links: [
      { type: "docs", url: "https://resend.com/docs/introduction" },
      { type: "api", url: "https://resend.com/docs/api-reference/introduction" },
      { type: "npm", url: "https://npmjs.com/package/resend" },
      { type: "github", url: "https://github.com/resend/resend-node" },
    ],
  },
  {
    name: "Upstash",
    slug: "upstash",
    description: "Serverless Redis and Kafka for the edge — JS/TS SDK",
    npm_package: "@upstash/redis",
    github_repo: "upstash/upstash-redis",
    docs_url: "https://upstash.com/docs/redis/overall/getstarted",
    tags: ["database", "redis", "serverless", "edge"],
    links: [
      { type: "docs", url: "https://upstash.com/docs/redis/sdks/ts/overview" },
      { type: "npm", url: "https://npmjs.com/package/@upstash/redis" },
      { type: "github", url: "https://github.com/upstash/upstash-redis" },
    ],
  },

  // ─── Runtimes ─────────────────────────────────────────────────────────────────
  {
    name: "Bun",
    slug: "bun",
    description: "Fast all-in-one JavaScript runtime with bundler, test runner, and package manager",
    npm_package: "bun-types",
    github_repo: "oven-sh/bun",
    docs_url: "https://bun.sh/docs",
    tags: ["runtime", "javascript", "typescript", "bundler"],
    links: [
      { type: "docs", url: "https://bun.sh/docs" },
      { type: "api", url: "https://bun.sh/docs/api/http" },
      { type: "npm", url: "https://npmjs.com/package/bun-types" },
      { type: "github", url: "https://github.com/oven-sh/bun" },
    ],
  },
  {
    name: "Deno",
    slug: "deno",
    description: "A modern runtime for JavaScript and TypeScript",
    npm_package: undefined,
    github_repo: "denoland/deno",
    docs_url: "https://docs.deno.com",
    tags: ["runtime", "javascript", "typescript", "secure"],
    links: [
      { type: "docs", url: "https://docs.deno.com/runtime" },
      { type: "api", url: "https://docs.deno.com/api/deno" },
      { type: "github", url: "https://github.com/denoland/deno" },
    ],
  },
  {
    name: "Node.js",
    slug: "nodejs",
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine",
    npm_package: undefined,
    github_repo: "nodejs/node",
    docs_url: "https://nodejs.org/en/docs",
    tags: ["runtime", "javascript", "server"],
    links: [
      { type: "docs", url: "https://nodejs.org/en/docs/guides" },
      { type: "api", url: "https://nodejs.org/api" },
      { type: "github", url: "https://github.com/nodejs/node" },
    ],
  },

  // ─── Mobile ───────────────────────────────────────────────────────────────────
  {
    name: "React Native",
    slug: "react-native",
    description: "Build native apps for Android and iOS using React",
    npm_package: "react-native",
    github_repo: "facebook/react-native",
    docs_url: "https://reactnative.dev/docs/getting-started",
    tags: ["mobile", "react", "android", "ios"],
    links: [
      { type: "docs", url: "https://reactnative.dev/docs/getting-started" },
      { type: "api", url: "https://reactnative.dev/docs/components-and-apis" },
      { type: "npm", url: "https://npmjs.com/package/react-native" },
      { type: "github", url: "https://github.com/facebook/react-native" },
    ],
  },
  {
    name: "Expo",
    slug: "expo",
    description: "An open-source platform for making universal native apps with React",
    npm_package: "expo",
    github_repo: "expo/expo",
    docs_url: "https://docs.expo.dev",
    tags: ["mobile", "react-native", "android", "ios", "web"],
    links: [
      { type: "docs", url: "https://docs.expo.dev/get-started/introduction" },
      { type: "api", url: "https://docs.expo.dev/versions/latest" },
      { type: "npm", url: "https://npmjs.com/package/expo" },
      { type: "github", url: "https://github.com/expo/expo" },
    ],
  },

  // ─── Utilities ────────────────────────────────────────────────────────────────
  {
    name: "date-fns",
    slug: "date-fns",
    description: "Modern JavaScript date utility library",
    npm_package: "date-fns",
    github_repo: "date-fns/date-fns",
    docs_url: "https://date-fns.org/docs",
    tags: ["utility", "dates", "javascript"],
    links: [
      { type: "docs", url: "https://date-fns.org/docs/Getting-Started" },
      { type: "api", url: "https://date-fns.org/v3/docs" },
      { type: "npm", url: "https://npmjs.com/package/date-fns" },
      { type: "github", url: "https://github.com/date-fns/date-fns" },
    ],
  },
  {
    name: "Lodash",
    slug: "lodash",
    description: "A modern JavaScript utility library delivering modularity and performance",
    npm_package: "lodash",
    github_repo: "lodash/lodash",
    docs_url: "https://lodash.com/docs",
    tags: ["utility", "javascript", "functional"],
    links: [
      { type: "docs", url: "https://lodash.com/docs" },
      { type: "npm", url: "https://npmjs.com/package/lodash" },
      { type: "github", url: "https://github.com/lodash/lodash" },
    ],
  },
  {
    name: "Effect",
    slug: "effect",
    description: "Powerful TypeScript framework for building complex applications",
    npm_package: "effect",
    github_repo: "Effect-TS/effect",
    docs_url: "https://effect.website/docs",
    tags: ["typescript", "functional", "effects", "fp"],
    links: [
      { type: "docs", url: "https://effect.website/docs/getting-started/introduction" },
      { type: "api", url: "https://effect-ts.github.io/effect" },
      { type: "npm", url: "https://npmjs.com/package/effect" },
      { type: "github", url: "https://github.com/Effect-TS/effect" },
    ],
  },

  // ─── Python ───────────────────────────────────────────────────────────────────
  {
    name: "FastAPI",
    slug: "fastapi",
    description: "Modern, fast web framework for building APIs with Python type hints",
    npm_package: undefined,
    github_repo: "fastapi/fastapi",
    docs_url: "https://fastapi.tiangolo.com",
    tags: ["python", "api", "framework", "async"],
    links: [
      { type: "docs", url: "https://fastapi.tiangolo.com/tutorial" },
      { type: "api", url: "https://fastapi.tiangolo.com/reference" },
      { type: "github", url: "https://github.com/fastapi/fastapi" },
    ],
  },
  {
    name: "Django",
    slug: "django",
    description: "The web framework for perfectionists with deadlines",
    npm_package: undefined,
    github_repo: "django/django",
    docs_url: "https://docs.djangoproject.com",
    tags: ["python", "framework", "web", "orm"],
    links: [
      { type: "docs", url: "https://docs.djangoproject.com/en/stable" },
      { type: "github", url: "https://github.com/django/django" },
    ],
  },
  {
    name: "Flask",
    slug: "flask",
    description: "A lightweight WSGI web application framework in Python",
    npm_package: undefined,
    github_repo: "pallets/flask",
    docs_url: "https://flask.palletsprojects.com",
    tags: ["python", "framework", "web", "wsgi"],
    links: [
      { type: "docs", url: "https://flask.palletsprojects.com/en/stable" },
      { type: "api", url: "https://flask.palletsprojects.com/en/stable/api" },
      { type: "github", url: "https://github.com/pallets/flask" },
    ],
  },
  {
    name: "SQLAlchemy",
    slug: "sqlalchemy",
    description: "The Python SQL toolkit and Object Relational Mapper",
    npm_package: undefined,
    github_repo: "sqlalchemy/sqlalchemy",
    docs_url: "https://docs.sqlalchemy.org",
    tags: ["python", "database", "orm", "sql"],
    links: [
      { type: "docs", url: "https://docs.sqlalchemy.org/en/20/tutorial" },
      { type: "api", url: "https://docs.sqlalchemy.org/en/20/orm/mapping_api.html" },
      { type: "github", url: "https://github.com/sqlalchemy/sqlalchemy" },
    ],
  },
  {
    name: "Pydantic",
    slug: "pydantic",
    description: "Data validation using Python type annotations",
    npm_package: undefined,
    github_repo: "pydantic/pydantic",
    docs_url: "https://docs.pydantic.dev",
    tags: ["python", "validation", "types"],
    links: [
      { type: "docs", url: "https://docs.pydantic.dev/latest" },
      { type: "api", url: "https://docs.pydantic.dev/latest/api/main" },
      { type: "github", url: "https://github.com/pydantic/pydantic" },
    ],
  },
  {
    name: "Pandas",
    slug: "pandas",
    description: "Powerful Python data analysis and manipulation library",
    npm_package: undefined,
    github_repo: "pandas-dev/pandas",
    docs_url: "https://pandas.pydata.org/docs",
    tags: ["python", "data-science", "dataframes", "analysis"],
    links: [
      { type: "docs", url: "https://pandas.pydata.org/docs/getting_started" },
      { type: "api", url: "https://pandas.pydata.org/docs/reference" },
      { type: "github", url: "https://github.com/pandas-dev/pandas" },
    ],
  },
  {
    name: "NumPy",
    slug: "numpy",
    description: "Fundamental package for scientific computing with Python",
    npm_package: undefined,
    github_repo: "numpy/numpy",
    docs_url: "https://numpy.org/doc",
    tags: ["python", "data-science", "arrays", "math"],
    links: [
      { type: "docs", url: "https://numpy.org/doc/stable/user/quickstart.html" },
      { type: "api", url: "https://numpy.org/doc/stable/reference" },
      { type: "github", url: "https://github.com/numpy/numpy" },
    ],
  },
  {
    name: "PyTorch",
    slug: "pytorch",
    description: "An open source machine learning framework for Python",
    npm_package: undefined,
    github_repo: "pytorch/pytorch",
    docs_url: "https://pytorch.org/docs",
    tags: ["python", "ml", "deep-learning", "tensors"],
    links: [
      { type: "docs", url: "https://pytorch.org/docs/stable/index.html" },
      { type: "api", url: "https://pytorch.org/docs/stable/torch.html" },
      { type: "github", url: "https://github.com/pytorch/pytorch" },
    ],
  },

  // ─── DevOps / Infra ───────────────────────────────────────────────────────────
  {
    name: "Docker",
    slug: "docker",
    description: "Build, run, and ship applications in containers",
    npm_package: undefined,
    github_repo: "docker/cli",
    docs_url: "https://docs.docker.com",
    tags: ["devops", "containers", "deployment"],
    links: [
      { type: "docs", url: "https://docs.docker.com/get-started" },
      { type: "api", url: "https://docs.docker.com/engine/api" },
      { type: "github", url: "https://github.com/docker/cli" },
    ],
  },
  {
    name: "GitHub Actions",
    slug: "github-actions",
    description: "Automate, customize, and execute software development workflows in GitHub",
    npm_package: undefined,
    github_repo: "actions/toolkit",
    docs_url: "https://docs.github.com/en/actions",
    tags: ["devops", "ci-cd", "automation"],
    links: [
      { type: "docs", url: "https://docs.github.com/en/actions/learn-github-actions" },
      { type: "api", url: "https://docs.github.com/en/rest/actions" },
      { type: "github", url: "https://github.com/actions/toolkit" },
    ],
  },
  {
    name: "Terraform",
    slug: "terraform",
    description: "Infrastructure as code tool to provision and manage cloud resources",
    npm_package: undefined,
    github_repo: "hashicorp/terraform",
    docs_url: "https://developer.hashicorp.com/terraform/docs",
    tags: ["devops", "infra-as-code", "cloud"],
    links: [
      { type: "docs", url: "https://developer.hashicorp.com/terraform/docs" },
      { type: "api", url: "https://developer.hashicorp.com/terraform/language" },
      { type: "github", url: "https://github.com/hashicorp/terraform" },
    ],
  },

  // ─── GraphQL ──────────────────────────────────────────────────────────────────
  {
    name: "GraphQL",
    slug: "graphql",
    description: "A query language for your API and a server-side runtime for executing queries",
    npm_package: "graphql",
    github_repo: "graphql/graphql-js",
    docs_url: "https://graphql.org/learn",
    tags: ["api", "query-language", "schema"],
    links: [
      { type: "docs", url: "https://graphql.org/learn" },
      { type: "api", url: "https://graphql.org/graphql-js" },
      { type: "npm", url: "https://npmjs.com/package/graphql" },
      { type: "github", url: "https://github.com/graphql/graphql-js" },
    ],
  },
  {
    name: "Apollo Client",
    slug: "apollo-client",
    description: "Comprehensive state management library for JavaScript that enables GraphQL",
    npm_package: "@apollo/client",
    github_repo: "apollographql/apollo-client",
    docs_url: "https://www.apollographql.com/docs/react",
    tags: ["graphql", "state-management", "react"],
    links: [
      { type: "docs", url: "https://www.apollographql.com/docs/react" },
      { type: "api", url: "https://www.apollographql.com/docs/react/api/core/ApolloClient" },
      { type: "npm", url: "https://npmjs.com/package/@apollo/client" },
      { type: "github", url: "https://github.com/apollographql/apollo-client" },
    ],
  },

  // ─── TypeScript Tools ─────────────────────────────────────────────────────────
  {
    name: "TypeScript",
    slug: "typescript",
    description: "Strongly typed programming language that builds on JavaScript",
    npm_package: "typescript",
    github_repo: "microsoft/TypeScript",
    docs_url: "https://www.typescriptlang.org/docs",
    tags: ["language", "typescript", "types"],
    links: [
      { type: "docs", url: "https://www.typescriptlang.org/docs/handbook/intro.html" },
      { type: "api", url: "https://www.typescriptlang.org/tsconfig" },
      { type: "npm", url: "https://npmjs.com/package/typescript" },
      { type: "github", url: "https://github.com/microsoft/TypeScript" },
    ],
  },
  {
    name: "ESLint",
    slug: "eslint",
    description: "Find and fix problems in your JavaScript/TypeScript code",
    npm_package: "eslint",
    github_repo: "eslint/eslint",
    docs_url: "https://eslint.org/docs",
    tags: ["tooling", "linting", "javascript", "typescript"],
    links: [
      { type: "docs", url: "https://eslint.org/docs/latest/use/getting-started" },
      { type: "api", url: "https://eslint.org/docs/latest/use/core-concepts" },
      { type: "npm", url: "https://npmjs.com/package/eslint" },
      { type: "github", url: "https://github.com/eslint/eslint" },
    ],
  },
  {
    name: "Prettier",
    slug: "prettier",
    description: "An opinionated code formatter for JavaScript, TypeScript, CSS, and more",
    npm_package: "prettier",
    github_repo: "prettier/prettier",
    docs_url: "https://prettier.io/docs/en",
    tags: ["tooling", "formatting", "javascript"],
    links: [
      { type: "docs", url: "https://prettier.io/docs/en/index.html" },
      { type: "npm", url: "https://npmjs.com/package/prettier" },
      { type: "github", url: "https://github.com/prettier/prettier" },
    ],
  },
  {
    name: "Biome",
    slug: "biome",
    description: "One toolchain for your web project — linter and formatter",
    npm_package: "@biomejs/biome",
    github_repo: "biomejs/biome",
    docs_url: "https://biomejs.dev/docs",
    tags: ["tooling", "linting", "formatting", "rust"],
    links: [
      { type: "docs", url: "https://biomejs.dev/guides/getting-started" },
      { type: "api", url: "https://biomejs.dev/reference/configuration" },
      { type: "npm", url: "https://npmjs.com/package/@biomejs/biome" },
      { type: "github", url: "https://github.com/biomejs/biome" },
    ],
  },

  // ─── Search / Vector DBs ──────────────────────────────────────────────────────
  {
    name: "Exa",
    slug: "exa",
    description: "AI-powered web search API for finding and retrieving relevant content",
    npm_package: "exa-js",
    github_repo: "exa-labs/exa-js",
    docs_url: "https://docs.exa.ai",
    tags: ["search", "ai", "api", "web"],
    links: [
      { type: "docs", url: "https://docs.exa.ai/reference/getting-started" },
      { type: "api", url: "https://docs.exa.ai/reference/search-endpoint" },
      { type: "npm", url: "https://npmjs.com/package/exa-js" },
      { type: "github", url: "https://github.com/exa-labs/exa-js" },
    ],
  },
  {
    name: "Firecrawl",
    slug: "firecrawl",
    description: "Turn any website into LLM-ready data — scraping and crawling API",
    npm_package: "@mendable/firecrawl-js",
    github_repo: "mendableai/firecrawl",
    docs_url: "https://docs.firecrawl.dev",
    tags: ["scraping", "crawling", "ai", "data"],
    links: [
      { type: "docs", url: "https://docs.firecrawl.dev/introduction" },
      { type: "api", url: "https://docs.firecrawl.dev/api-reference/introduction" },
      { type: "npm", url: "https://npmjs.com/package/@mendable/firecrawl-js" },
      { type: "github", url: "https://github.com/mendableai/firecrawl" },
    ],
  },
];
